import { insertAtCursor, setStatus } from "./app.js";

// --- Utilities ---

function pick(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

// --- Markov Engine ---

function markovName(cfg) {
  const { table, minLen, maxLen, fallbacks } = cfg;
  let attempts = 0;
  while (attempts < 100) {
    let state = pick(table["^"]);
    let name = state;
    let steps = 0;
    while (steps < 20) {
      const successors = table[state];
      if (!successors) break;
      const token = pick(successors);
      if (token === ".") break;
      name += token;
      state = token;
      steps++;
    }
    const capitalised = name[0].toUpperCase() + name.slice(1).toLowerCase();
    if (capitalised.length >= minLen && capitalised.length <= maxLen) {
      return capitalised;
    }
    attempts++;
  }
  const fallback = pick(fallbacks);
  return fallback[0].toUpperCase() + fallback.slice(1).toLowerCase();
}

// --- Culture Data ---

const CULTURES = {
  human: {
    male: {
      table: {
        "^": ["al", "ed", "ro", "wu", "go", "ha", "le", "br", "th", "ed", "ro", "al", "ga", "ce", "os", "wi", "be", "co", "si", "ra", "er", "ba", "gu", "he", "in", "lo", "ma", "no", "os", "re", "st", "to", "ul", "va", "we", "al", "bj", "cl", "di", "el", "al", "al", "be", "ea", "go", "ha", "le", "ro", "si", "wa"],
        "al": ["ld", "ld", "la", "ld", "ld", "ld", "ld", "lb", "lf", "ld"],
        "ld": ["dr", ".", "dr", ".", "de", "dw", ".", "dr"],
        "dr": ["ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri"],
        "ri": ["ic", "ic", "ic", "in", "ic", "ic", "ic", "ic", "ic", "ik", "ic", "ic", "ic", "ic", "ic", "ic", "ic", "ic"],
        "ic": [".", ".", ".", ".", ".", ".", ".", ".", ".", "ch", ".", ".", ".", ".", ".", "."],
        "ed": ["dm", "dr", "dr", ".", "dw"],
        "dm": ["mu"],
        "mu": ["un", "un", "un"],
        "un": ["nd", "nd", "nt", "nd"],
        "nd": [".", ".", ".", "."],
        "ro": ["ol", "ow", "od"],
        "ol": ["la", "ld"],
        "la": ["an", "ar"],
        "an": ["nd", ".", "."],
        "wu": ["ul"],
        "ul": ["lf", "lr"],
        "lf": ["fr", "fr", "fw"],
        "fr": ["ri", "ri", "re"],
        "go": ["od", "od"],
        "od": ["dw", "dr", "dr"],
        "dw": ["wi", "wi", "wi", "wi"],
        "wi": ["in", "il", "in", "in", "in", "in", "ig"],
        "in": [".", ".", ".", "ng", "nh", ".", ".", "."],
        "ha": ["ar", "ar", "ar", "ad"],
        "ar": ["ra", "ri", "re", ".", ".", ".", "rd", "."],
        "ra": ["al", "ad", "ag"],
        "le": ["eo", "ed"],
        "eo": ["of", "or"],
        "of": ["fr"],
        "br": ["re", "ri"],
        "re": ["en", "et", "ed", "ei"],
        "en": ["nn", "nr", ".", "."],
        "nn": ["na"],
        "na": ["an", "ar"],
        "th": ["ho", ".", "he", "ha"],
        "ho": ["or"],
        "or": ["ri", "rn", "rb", "rs", "rn"],
        "ow": ["wa"],
        "wa": ["an", "al", "al"],
        "ga": ["ar"],
        "et": ["th", "tr"],
        "ce": ["ed"],
        "os": ["sr", "sw"],
        "sr": ["ri"],
        "il": ["lf"],
        "be": ["eo", "er", "er"],
        "rn": [".", "ne", "."],
        "co": ["on"],
        "on": ["nr"],
        "nr": ["ra", "ri"],
        "ad": [".", "dr", "dw"],
        "si": ["ig", "ig"],
        "ig": ["gm", ".", "gr"],
        "gm": ["mu"],
        "ag": ["gn", "gn"],
        "gn": ["na", "nu"],
        "er": ["rw", ".", "rt", "rn", ".", "rt"],
        "rw": ["wi"],
        "ba": ["al"],
        "gu": ["un"],
        "nt": ["th"],
        "he": ["er", "en"],
        "ik": ["."],
        "ng": ["gv"],
        "gv": ["va"],
        "va": ["ar", "al"],
        "lo": ["ot", "ov"],
        "ot": ["th"],
        "ma": ["ag", "ar"],
        "nu": ["us"],
        "us": ["."],
        "no": ["or"],
        "rb": ["be"],
        "rt": [".", "to"],
        "sw": ["wa"],
        "ei": ["in"],
        "nh": ["ha"],
        "rd": ["."],
        "st": ["te", "te"],
        "te": ["ef", "en"],
        "ef": ["ff"],
        "ff": ["fe"],
        "fe": ["en"],
        "to": ["or", "ol"],
        "rs": ["st"],
        "lr": ["ri"],
        "de": ["em"],
        "em": ["ma"],
        "we": ["er"],
        "ne": ["er"],
        "bj": ["jo"],
        "jo": ["or"],
        "cl": ["lo"],
        "ov": ["vi"],
        "vi": ["is"],
        "is": ["."],
        "di": ["ie"],
        "ie": ["et"],
        "tr": ["ri"],
        "ch": ["."],
        "el": ["lm"],
        "lm": ["mu"],
        "lb": ["br"],
        "fw": ["wi"],
        "ea": ["ad"],
        "gr": ["ri"]
      },
      minLen: 4,
      maxLen: 10,
      fallbacks: ["Aldric", "Edmund", "Gareth"]
    },
    female: {
      table: {
        "^": ["mi", "ed", "ro", "wi", "gw", "al", "su", "br", "el", "fr", "hi", "in", "ka", "li", "as", "si", "th", "yr", "da", "ei", "gu", "he", "is", "ra", "sv", "th", "ul", "va", "ae", "be", "el", "ge", "id", "li", "ma", "ne", "pe", "so", "to", "wy", "al", "br", "ed", "gw", "hi", "le", "mi", "ra", "si", "wu"],
        "mi": ["ir", "il"],
        "ir": ["ra", "ra"],
        "ra": [".", ".", ".", ".", "ag", ".", ".", "an"],
        "ed": ["di", "dw"],
        "di": ["it", "it", "is"],
        "it": ["th", "th", "th", "th", "th"],
        "th": [".", ".", "ho", "hy", ".", ".", "."],
        "ro": ["ow"],
        "ow": ["we"],
        "we": ["en", "en"],
        "en": ["na", ".", ".", "nn"],
        "na": [".", ".", ".", "."],
        "wi": ["il", "it"],
        "il": ["ll", "ld", "ld", "ld", "ld", "ld"],
        "ll": ["la", "la"],
        "la": [".", "ar", ".", "."],
        "gw": ["we", "wy"],
        "al": ["ld", "ld", "ld"],
        "ld": ["di", ".", "da", "de", "di", ".", "dw", "dr", "da"],
        "su": ["un"],
        "un": ["nn", "."],
        "nn": ["ni", "ne", "ne", "na", "nv"],
        "ni": ["iv"],
        "iv": ["va", "vi"],
        "va": [".", "al", "."],
        "br": ["ry", "re"],
        "ry": ["yn"],
        "yn": ["nh", "nn", ".", ".", "na", "."],
        "nh": ["hi"],
        "hi": ["il", "il", "il", "il"],
        "el": ["la", "lg", "li", "lf"],
        "ar": ["ra", "re"],
        "fr": ["re"],
        "re": ["ey", "en", "en"],
        "ey": ["ya"],
        "ya": ["."],
        "da": [".", "ag", ".", "."],
        "in": ["ng", "nn"],
        "ng": ["gr"],
        "gr": ["ri", "ri", "ri"],
        "ri": ["id", "id", "id", "is", "it"],
        "id": [".", ".", ".", "dr"],
        "ka": ["at"],
        "at": ["tl"],
        "tl": ["la"],
        "li": ["in", "it", "iv"],
        "ne": ["ea", "es", "."],
        "ea": [".", "."],
        "as": ["st"],
        "st": ["tr"],
        "tr": ["ri", "ra"],
        "si": ["ig", "ig"],
        "ig": ["gr", ".", ".", "gr"],
        "ho": ["or"],
        "or": ["ra"],
        "yr": ["rs", "ra"],
        "rs": ["sa"],
        "sa": [".", "."],
        "ag": ["gn", "gn"],
        "gn": ["ny", "na"],
        "ny": ["."],
        "ei": ["ir", "ig", "ig"],
        "gu": ["ud"],
        "ud": ["dr"],
        "dr": ["ru", "ri", "."],
        "ru": ["un"],
        "he": ["el"],
        "lg": ["ga"],
        "ga": ["."],
        "is": ["so", ".", "."],
        "so": ["ol", "ol"],
        "ol": ["ld", "lv"],
        "de": ["."],
        "sv": ["ve"],
        "ve": ["ea", "ei", "ei"],
        "hy": ["yr"],
        "ul": ["ll", "lf"],
        "ae": ["el"],
        "be": ["er"],
        "er": ["rt", "rd"],
        "rt": ["ta"],
        "ta": ["."],
        "lf": ["fh", "fw"],
        "fh": ["hi"],
        "ge": ["er"],
        "rd": ["da"],
        "vi": ["ia"],
        "ia": ["."],
        "ma": ["ar"],
        "es": ["ss"],
        "ss": ["sa"],
        "pe": ["et"],
        "et": ["tr"],
        "lv": ["ve"],
        "to": ["ov"],
        "ov": ["va"],
        "wy": ["yn", "yn", "yn", "yn", "yn"],
        "dw": ["wy", "wy"],
        "le": ["ew"],
        "ew": ["wi"],
        "an": ["nn"],
        "nv": ["ve"],
        "wu": ["ul"],
        "fw": ["wy"]
      },
      minLen: 3,
      maxLen: 10,
      fallbacks: ["Mira", "Freya", "Astrid"]
    },
    surname: {
      table: {
        "^": ["th", "co", "bl", "as", "wr", "du", "ir", "st", "oa", "ra", "wi", "gr", "ha", "br", "mo", "co", "de", "fa", "go", "he", "ki", "lo", "ni", "ol", "pi", "qu", "re", "si", "ta", "un", "wo", "as", "br", "du", "el", "fo", "gr", "ho", "iv", "ke", "ma", "ne", "ra", "st", "ti", "wh", "ya", "em", "fe", "cr"],
        "th": ["ho", ".", "hs", "ho", "."],
        "ho": ["or", "ol", "or", "ol", "ol", "ol"],
        "or": ["rn", ".", "rd", "re", "rt", "rf", "rn", "rt", "rd", "rd", "."],
        "rn": ["nw", "ne", ".", "nh"],
        "nw": ["wo", "wo"],
        "wo": ["oo", "or", "ol", "oo", "or", "oo", "oo"],
        "oo": ["od", "or", "or", "ok", "od", "od", "or", "od"],
        "od": [".", ".", ".", "."],
        "co": ["ol", "op"],
        "ol": ["ld", "ll", "ld", "ld", "lf", "ll", "ll", "lt"],
        "ld": ["dw", ".", "dl", "dc", "de", "."],
        "dw": ["we"],
        "we": ["el"],
        "el": ["ll", "lm", "ld", "ld", "ld"],
        "ll": [".", "lo", ".", "lo", ".", "lo", "lo"],
        "bl": ["la"],
        "la": ["ac"],
        "ac": ["ck"],
        "ck": ["km", "ks", ".", "."],
        "km": ["mo"],
        "mo": ["oo", "or", "oo", "oo"],
        "as": ["sh", "st", "sh"],
        "sh": ["hf", "ha", "hw", "ha", "hw"],
        "hf": ["fo"],
        "fo": ["or", "ox", "or", "or"],
        "rd": [".", ".", "."],
        "wr": ["re"],
        "re": ["en", ".", "ey", ".", "ed", ".", ".", "es"],
        "en": ["ns", "nc", "nw"],
        "ns": ["sh"],
        "ha": ["aw", "aw", "aw"],
        "aw": [".", "wk", "."],
        "du": ["un", "us"],
        "un": ["nm", "nd"],
        "nm": ["mo"],
        "ir": ["ro", "rw"],
        "ro": ["on", "of", "oo", "ov", "ow"],
        "on": ["nv", "ne", "ne", "ng", "ne"],
        "nv": ["va"],
        "va": ["al"],
        "al": ["le", "ll", "ll", "le"],
        "le": [".", "ea", ".", "ew", "ef", "."],
        "st": ["to", "to", "tl", ".", "to", "tw"],
        "to": ["on", "on", "on"],
        "ne": ["eh", ".", ".", ".", "eh", ".", "et", "eg"],
        "eh": ["he", "hu"],
        "he": ["el", "ea"],
        "lm": ["."],
        "oa": ["ak"],
        "ak": ["kr"],
        "kr": ["ri"],
        "ri": ["id", "ig", "ia", "im"],
        "id": ["dg"],
        "dg": ["ge"],
        "ge": ["."],
        "ra": ["av", "av"],
        "av": ["ve", "ve"],
        "ve": ["en", "er", "er", ".", ".", "en"],
        "nc": ["cr"],
        "cr": ["ro", "re"],
        "of": ["ft"],
        "ft": ["."],
        "wi": ["in", "in", "ic", "ic"],
        "in": ["nt", "nd", "ng", "ne"],
        "nt": ["te"],
        "te": ["er", "er", ".", "."],
        "er": ["rb", ".", "rg", "re", ".", "rb", "re", "rh", "rg", "re", "rh", "rm", "rn"],
        "rb": ["bo", "br"],
        "bo": ["ou"],
        "ou": ["ur"],
        "ur": ["rn", "rs"],
        "gr": ["re", "ro", "ri"],
        "ey": ["ym"],
        "ym": ["ma", "me"],
        "ma": ["an", "ar", "ar"],
        "an": ["ne", "ne"],
        "wk": ["ks"],
        "ks": ["sw", "si"],
        "sw": ["wo"],
        "rt": ["th", "th", "th"],
        "br": ["ri", "ro", "ri"],
        "ig": ["gh", "gh"],
        "gh": ["ht", "ht"],
        "ht": ["tw", "tf"],
        "tw": ["wa", "wo"],
        "wa": ["at"],
        "at": ["te", "te", "te"],
        "rf": ["fi"],
        "fi": ["ie", "ie"],
        "ie": ["el", "el"],
        "op": ["pp"],
        "pp": ["pe"],
        "pe": ["er"],
        "rg": ["ga", "gr"],
        "ga": ["at", "at"],
        "de": ["ee", "er", "er"],
        "ee": ["ep"],
        "ep": ["ph"],
        "ph": ["ho"],
        "lo": ["ow", "on", "ow", "ov", "ow", "ow"],
        "ow": [".", "wm", "wf", ".", "wd"],
        "fa": ["ai", "al"],
        "ai": ["ir"],
        "rw": ["wi"],
        "nd": [".", "de"],
        "go": ["ol"],
        "dl": ["le"],
        "ea": ["af", "ar"],
        "af": ["."],
        "ar": ["rt", "rk", "rc", "rs", "rr"],
        "hs": ["st"],
        "ki": ["in"],
        "ng": ["gs", "gm"],
        "gs": ["sm"],
        "sm": ["ma"],
        "rk": ["."],
        "gm": ["me"],
        "me": ["er", "er", "er"],
        "ni": ["ig"],
        "tf": ["fa", "fo"],
        "dc": ["ca"],
        "ca": ["as"],
        "tl": ["le", "le", "le"],
        "pi": ["in"],
        "hu": ["ur"],
        "rs": ["st", "sh"],
        "qu": ["ui"],
        "ui": ["ic"],
        "ic": ["ck", "ck", "ck"],
        "si": ["il", "il"],
        "il": ["lv", "lv", "ll"],
        "lv": ["ve", "ve"],
        "ed": ["dt"],
        "dt": ["th"],
        "ok": ["."],
        "ta": ["al"],
        "wm": ["me"],
        "rh": ["hi", "ho"],
        "hi": ["il", "it"],
        "lf": ["fs"],
        "fs": ["sb"],
        "sb": ["ba"],
        "ba": ["an"],
        "hw": ["wi", "wi"],
        "ia": ["ar"],
        "rc": ["cl"],
        "cl": ["li"],
        "li": ["if"],
        "if": ["ff"],
        "ff": ["."],
        "us": ["sk"],
        "sk": ["kw"],
        "kw": ["wo"],
        "ov": ["ve", "ve"],
        "ox": ["xg"],
        "xg": ["gl"],
        "gl": ["lo"],
        "im": ["ms", "mb"],
        "ms": ["sh"],
        "wf": ["fi"],
        "iv": ["vy"],
        "vy": ["ym"],
        "ke": ["et"],
        "et": ["tt", "tt"],
        "tt": ["tl", "tl"],
        "ew": ["wo"],
        "ef": ["fo"],
        "eg": ["ga"],
        "ti": ["im"],
        "mb": ["be", "be"],
        "be": ["er", "er"],
        "wh": ["hi"],
        "it": ["tf"],
        "ya": ["ar"],
        "rr": ["ro"],
        "wd": ["da"],
        "da": ["al"],
        "em": ["mb"],
        "rm": ["mo"],
        "fe": ["er"],
        "nh": ["ho"],
        "lt": ["."],
        "es": ["st"]
      },
      minLen: 5,
      maxLen: 14,
      fallbacks: ["Thornwood", "Ashford", "Ironvale"]
    }
  }
};

// --- Generators ---

function generatePersonName(culture, variant) {
  const data = CULTURES[culture];
  if (!data) {
    setStatus("Unknown culture: " + culture);
    return null;
  }
  const variantData = data[variant];
  if (!variantData) {
    setStatus("Unknown variant: " + variant);
    return null;
  }
  if (variant === "surname") {
    const surname = markovName(variantData);
    return "> 👤 Human Surname: " + surname;
  }
  const first = markovName(variantData);
  const surname = markovName(data.surname);
  const label = variant === "male" ? "Human Male" : "Human Female";
  return "> 👤 " + label + ": " + first + " " + surname;
}

// --- UI Wiring ---

document.getElementById("btn-namegen-person").addEventListener("click", () => {
  const culture = document.getElementById("namegen-culture").value;
  const variant = document.getElementById("namegen-variant").value;
  const result = generatePersonName(culture, variant);
  if (result) {
    insertAtCursor(result);
  }
});
