import { insertAtCursor, setStatus } from "./app.js";

// --- Utilities ---

function pick(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

function combine(slots) {
  return slots.map(slot => pick(slot)).join("");
}

function cap(str) {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

// --- Markov Engine ---

function markovName(cfg) {
  const { table, minLen, maxLen, fallbacks } = cfg;
  let attempts = 0;
  while (attempts < 100) {
    let state = pick(table["^"]);
    let name = state;
    let steps = 0;
    while (steps < 20) {
      const successors = table[state];
      if (!successors) break;
      const token = pick(successors);
      if (token === ".") break;
      name += token[1];
      state = token;
      steps++;
    }
    const capitalised = name[0].toUpperCase() + name.slice(1).toLowerCase();
    if (capitalised.length >= minLen && capitalised.length <= maxLen) {
      return capitalised;
    }
    attempts++;
  }
  const fallback = pick(fallbacks);
  return fallback[0].toUpperCase() + fallback.slice(1).toLowerCase();
}

// --- Culture Data ---

const CULTURES = {
  human: {
    male: {
      table: {
        "^": ["al", "ed", "ro", "wu", "go", "ha", "le", "br", "th", "ed", "ro", "al", "ga", "ce", "os", "wi", "be", "co", "si", "ra", "er", "ba", "gu", "he", "in", "lo", "ma", "no", "os", "re", "st", "to", "ul", "va", "we", "al", "bj", "cl", "di", "el", "ea", "go", "ha", "le", "ro", "si", "wa", "al", "be", "ea", "fa", "ge", "ha", "iv", "jo", "ke", "la", "me", "ni", "od", "pe", "ra", "so", "th", "ul", "vi", "wu", "al", "co", "dr", "er", "fe", "gi", "ha", "ir", "jo", "ke", "lo", "ma", "ni", "os", "pe", "qu", "ra", "si", "to", "ut", "va", "we", "al", "br", "ca", "de", "ed", "fo", "ga", "ha", "in", "ja", "ka", "le", "mo", "ni", "or", "ph", "ro", "st", "tr", "ut", "va", "wa", "ad", "bo", "co", "da", "el", "fe", "go", "ha", "is", "ja", "ke", "li", "ma", "no", "os", "pa", "re", "sv", "th", "ul", "vi", "wo", "ar", "br", "co", "di", "eg", "fl", "gr", "ha", "iv", "jo", "kn", "lu", "me", "nj", "or", "pr", "ru", "se", "th", "ul", "vi", "wy", "al", "be", "co", "dr", "ed", "fa", "gr", "ha", "is", "ja", "ke", "lo", "mi", "ne", "oe", "pr", "ra", "sk", "th", "ul", "va", "wi", "an", "bo", "ce", "da", "ed", "fe", "gu", "ha", "is", "jo", "ke", "lo", "ma", "no", "os", "pe"],
        "al": ["ld", "ld", "la", "ld", "ld", "ld", "ld", "ld", "ld", "lk", "ld", "ld", "ld", "ls", "ld", "ll", "ld", "ld", "ld", "lr", "ld", "lv", ".", "ld", "lv", "ld", "ld", "lr", "ld", "lo", "lv", "lr"],
        "ld": ["dr", ".", "dr", ".", "de", "dw", "da", "de", "do", ".", "dr", "dr", "dr", "dh", "de", "de", "dr", ".", ".", ".", ".", "dr", "."],
        "dr": ["ri", "ri", "ri", "ri", "ri", "ri", "re", "ru", "ri", "ri", "ri", "ri", "ri", "re", "ri", "ri", "ri", "ra", "ri", "ri", "ri"],
        "ri": ["ic", "ic", "ic", "in", "ic", "ic", "ic", "ic", "ic", "ik", "ic", "ic", "ic", "ic", "ik", "ic", "ic", "ic", "ic", "ic", "in", "ic", "ic", "ic", "ic", "ic", "ic", "ic", "is", "ic", "ic", "ic", "ic", "ig", "ic", "ia", "if", "ic", "ik", "ic", "im", "ic", "ic", "ic", "is", "ic", "ic", "ic", "ic", "in"],
        "ic": [".", ".", ".", ".", ".", ".", ".", ".", ".", "ch", ".", ".", ".", ".", ".", ".", ".", ".", ".", "ck", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", "ce", ".", ".", ".", ".", "."],
        "ed": ["dm", "dr", "dr", ".", "de", ".", "dr", "dw", ".", "dr", ".", "dg", "dw", "dm"],
        "dm": ["mu", "mu", "mo"],
        "mu": ["un", "un", "un", "un", "un", "un", "un", "un", "un"],
        "un": ["nd", "nd", "nt", "nd", "nd", "nd", "nd", "nd", "nd", "nd", "nd", "nd"],
        "nd": [".", ".", ".", ".", "de", "dr", ".", ".", "do", "de", ".", "dr", ".", ".", ".", ".", ".", ".", ".", "dr", "."],
        "ro": ["ol", "ow", "od", "on", "or", "on", "os", "os"],
        "ol": ["la", "lm", "lf", "lf", "lb", "ld"],
        "la": ["an", "ar", "ar", "an", "an", "an", "as", "an", "an"],
        "an": ["nd", ".", ".", ".", "nd", ".", ".", "nd", ".", ".", ".", "nd", "nt", ".", ".", ".", "ne", ".", "nd", ".", "ns", "."],
        "wu": ["ul", "ul"],
        "ul": ["lf", "lr", "lf", "lf", "lf", "la", "lb", "."],
        "lf": ["fr", "fr", ".", "fs", ".", "fr", "fr"],
        "fr": ["ri", "ri", "re", "re", "ra"],
        "go": ["od", "od", ".", "od", "oo"],
        "od": ["dw", "dr", "de", "di", "de", "dm", "."],
        "dw": ["wi", "wi", "wi", "wy", "wi"],
        "wi": ["in", "il", "in", "in", "in", "in", "il", "in"],
        "in": [".", ".", ".", "ng", "nh", ".", ".", ".", ".", "ng", ".", ".", ".", "nn", "."],
        "ha": ["ar", "ar", "ar", "al", "ar", "al", "al", "al", "al", "an", "ag", "am", "al"],
        "ar": ["ra", "ri", "re", ".", ".", ".", "rd", ".", "rd", "rd", ".", "rs", "rr", "re", "re", "ro", "rd", "rl", ".", "ru", ".", ".", "rd", "ra"],
        "ra": ["al", "ad", "ag", "am", "ag", "an", "an", "am", "am", "al", "av", "al", "ag"],
        "le": ["eo", "ea", "eo"],
        "eo": ["of", "or", "on", "or"],
        "of": ["fr"],
        "br": ["re", "ra", "ry", "re"],
        "re": ["en", "et", "ed", "ei", "en", "ed", "ed", "en", "es", "et", "ed", "ek", "el", "ei", "ed", "en", "en", "ec", "eg"],
        "en": ["nn", "nr", ".", ".", ".", ".", "nd", ".", ".", "nr", ".", ".", "nd", ".", ".", ".", "nd", ".", ".", ".", ".", "nz", "nt"],
        "nn": ["na", "."],
        "na": ["an", "ar"],
        "th": ["ho", ".", "he", "ha", "he", "he", ".", "hr", "ha", "ho", "ho", "ho"],
        "ho": ["or", "or", "ol", "or"],
        "or": ["ri", "rn", "rb", "rs", "rn", ".", "ri", "re", "rm", "rc", "rn", "re", "rr", "ri", "rt", "ri", "ri", "rw", "rc", ".", "ri", "rg", "rm", "ra", "rm", "re", ".", "rv", ".", "ri", "rd"],
        "ow": ["wa"],
        "wa": ["an", "al", "ar", "al", "al"],
        "ga": ["ar", "ar", "ar"],
        "et": ["th", "tr", "th", "ti"],
        "ce": ["ed", ".", ".", "ed"],
        "os": ["sr", "sw", "sb", "ss", "sg", "sp", "sm"],
        "sr": ["ri", "ri"],
        "il": ["lf", "ls", "ll", "lh", "."],
        "be": ["eo", "er", "er", "er", "er"],
        "rn": [".", "ne", ".", "."],
        "co": ["on", "ol", "or", "ol", "or"],
        "on": ["nr", ".", ".", ".", "nd", ".", "nd"],
        "nr": ["ra", "ri", "ri"],
        "ad": [".", "dw", "dr", "do", "dr"],
        "si": ["ig", "ig", "ig"],
        "ig": ["gm", "gu", "gg", "gr", ".", "gm"],
        "gm": ["mu", "mu"],
        "ag": ["gn", "gn", "gn", "ge", "gn", "gf"],
        "gn": ["na", "nu", "nv", "no"],
        "er": ["rw", ".", "rt", "rn", ".", ".", "ri", "rt", "rh", "rr", ".", "ro", "rl", "rr", ".", ".", "rt", "rr", ".", "rt", ".", "ri", "rg", "re"],
        "rw": ["wi", "wi"],
        "ba": ["al"],
        "gu": ["un", "ur", "us", "un"],
        "nt": ["th", ".", "ti"],
        "he": ["er", "en", "er", "er", "el", "el", "el"],
        "ik": [".", ".", "kl", "kt", ".", "ka"],
        "ng": ["gv", "gr"],
        "gv": ["va"],
        "va": ["ar", "al", "ar", "al", "al", "ar", "ar", "ar", "ar", "al", "al"],
        "lo": ["ot", "ov", "or", "or", "or", "or", "ot"],
        "ot": ["th", "tr"],
        "ma": ["ag", "ar", "al", "ad", "ac", "al"],
        "nu": ["us", "ut"],
        "us": [".", "st", ".", "."],
        "no": ["or", "or", "or", "or"],
        "rb": ["be"],
        "rt": [".", "tr", "te", ".", "th"],
        "sw": ["wa"],
        "ei": ["in", "id"],
        "nh": ["ha"],
        "rd": [".", ".", "de", ".", ".", ".", "dr"],
        "st": ["te", "te", "ta", "ta", "te", ".", "te", "ta", "ta"],
        "te": ["ef", "en", "en", "en", "ef"],
        "ef": ["ff", "fa", ".", "."],
        "ff": ["fe", "fi"],
        "fe": ["en", "en", "en", "er"],
        "to": ["or", "or", "or"],
        "rs": ["st", "se"],
        "lr": ["ri", "ri", "ri", "ri", "ri"],
        "de": ["em", "er", "er", "en", "en", "er", "eo", "el", "er", "es", "en", "en"],
        "em": ["ma"],
        "we": ["er", "en"],
        "ne": ["er", ".", "el"],
        "bj": ["jo"],
        "jo": ["or", "or", "or", "or", "ok"],
        "cl": ["lo"],
        "ov": ["vi"],
        "vi": ["is", "ig", "ik", "ig"],
        "is": [".", "st", "sr", "sm", ".", "sl"],
        "di": ["ie", "in", "ir"],
        "ie": ["et", "ef", "ef"],
        "tr": ["ri", "ra", "ri", "ri"],
        "ch": [".", "ht"],
        "el": ["lm", "ll", ".", "lm", ".", "la", "ld", ".", "lr", "ld", ".", "ls", "lm", "lm"],
        "lm": ["mu", ".", ".", ".", "."],
        "ea": ["ad", "an", "am"],
        "da": ["an", "ar", "ar", "ag", "an"],
        "ur": ["rd"],
        "am": [".", "mo", ".", ".", "mu"],
        "mo": ["on", "on", "or", "on"],
        "fa": ["al", "an", "ar"],
        "lk": ["."],
        "ge": ["er", "en", "en"],
        "rh": ["ha"],
        "do": ["or", "ol", "oc"],
        "iv": ["va", "va"],
        "ke": ["en", "el", "ed", "el", "et"],
        "se": ["en", "el", "el"],
        "me": ["er", "er"],
        "rr": ["ri", "ri", "re", "ri", "ri"],
        "ni": ["il", "ia", "ik"],
        "ls": [".", "st", "."],
        "pe": ["ed", "er", "er", "er", "er"],
        "nv": ["va"],
        "so": ["or"],
        "gg": ["go"],
        "fs": ["st"],
        "ta": ["an", "an", "an", "an"],
        "ru": ["us", "un", "uf"],
        "rl": ["la", "."],
        "gi": ["id"],
        "id": ["de", "da"],
        "ir": ["re", "rk"],
        "rm": ["mu", ".", "ma"],
        "ll": ["la", ".", "la"],
        "rc": ["ca", "cr"],
        "ca": ["an", "al"],
        "ia": ["al", "an"],
        "sb": ["bo"],
        "bo": ["or", "od", "or"],
        "qu": ["ui"],
        "ui": ["il"],
        "gr": ["ri", "ra", "ri", "ri", "ri", "ri"],
        "ut": ["th", "th", "."],
        "dh": ["he"],
        "es": ["sm", "st"],
        "sm": ["mo", "mu", "mu"],
        "wy": ["yn", "ys"],
        "yn": ["."],
        "fo": ["or"],
        "ck": ["."],
        "ja": ["ar", "ar", "al", "as"],
        "ka": ["ae", "ae", "al"],
        "ae": ["el", "el"],
        "kl": ["la"],
        "as": [".", "sp"],
        "ph": ["he"],
        "hr": ["re"],
        "ek": ["."],
        "lv": ["va", "va", "vd"],
        "li": ["ie", "ie"],
        "oc": ["."],
        "cr": ["ro"],
        "ss": ["."],
        "sg": ["go"],
        "oo": ["od"],
        "pa": ["ad"],
        "sv": ["ve"],
        "ve": ["en", "en"],
        "kt": ["to"],
        "wo": ["ol"],
        "ry": ["yc"],
        "yc": ["ce"],
        "lb": ["be", "br"],
        "rk": ["."],
        "eg": ["gr", "gr"],
        "fl": ["lo"],
        "if": ["ff"],
        "fi": ["in", "in"],
        "rg": ["ge", "gu"],
        "kn": ["nu"],
        "lu": ["ud"],
        "ud": ["dr"],
        "nj": ["ja"],
        "pr": ["ro", "re"],
        "sp": ["pe", "pe"],
        "uf": ["fu"],
        "fu": ["us"],
        "ys": ["st"],
        "ac": ["."],
        "av": ["ve"],
        "dg": ["ga"],
        "im": ["mw"],
        "mw": ["wa"],
        "nz": ["."],
        "mi": ["ik"],
        "oe": ["er"],
        "ti": ["ic", "il"],
        "sk": ["ka"],
        "rv": ["va"],
        "ec": ["ch"],
        "ht": ["."],
        "lh": ["he"],
        "ns": ["se"],
        "gf": ["fi"],
        "vd": ["da"],
        "sl": ["li"],
        "ok": ["ku"],
        "ku": ["ul"]
      },
      minLen: 4,
      maxLen: 10,
      fallbacks: ["Aldric", "Edmund", "Gareth"]
    },
    female: {
      table: {
        "^": ["mi", "ed", "ro", "wi", "gw", "al", "su", "br", "el", "fr", "hi", "in", "ka", "li", "as", "si", "th", "yr", "da", "ei", "gu", "he", "is", "ra", "sv", "th", "ul", "va", "ae", "be", "el", "ge", "li", "ma", "ne", "pe", "so", "to", "wy", "al", "br", "ed", "fe", "gi", "hr", "id", "jo", "ke", "la", "ma", "no", "ol", "re", "si", "to", "un", "vi", "wr", "as", "da", "ey", "fr", "gu", "he", "in", "ju", "ka", "li", "ma", "nj", "od", "ra", "si", "th", "ul", "vi", "yl", "al", "bo", "ce", "di", "el", "fr", "gr", "he", "il", "jo", "kj", "lo", "ma", "no", "ol", "ra", "si", "tu", "ur", "va", "ae", "be", "da", "em", "fj", "gu", "ha", "in", "ja", "ko", "lj", "my", "ne", "oy", "ra", "sk", "to", "un", "vi", "we", "as", "br", "ce", "do", "es", "fo", "gr", "hj", "id", "jo", "ka", "lo", "ma", "na", "od", "ru", "sa", "ti", "un", "va", "al", "bi", "cl", "da", "ei", "fr", "ge", "he", "il", "ja", "ko", "li", "mo", "ne", "ot", "re", "sv", "th", "ul", "ve", "ar", "bo", "do", "ey", "fa", "gr", "ha", "in", "jo", "kr", "lj", "mo", "ni", "ol", "ra", "si", "th", "ul", "va"],
        "mi": ["ir"],
        "ir": ["ra", "ra", "rn", ".", "ra"],
        "ra": [".", ".", ".", ".", "ag", ".", ".", ".", "an", "an", "ag", ".", ".", ".", ".", ".", "ak", "ag"],
        "ed": ["di", "dl", "dd", "di"],
        "di": ["it", "it", "is", "is", "is", "il", "il", "is", ".", "is", "is", "is", "is", "is"],
        "it": ["th", "th", "th", "tt"],
        "th": [".", ".", "ho", "hy", ".", "ha", "ha", ".", "ho", "hi", "he", "hi", "hu", "hr", "ho"],
        "ro": ["ow", "oa"],
        "ow": ["we"],
        "we": ["en", "en", "en", "en"],
        "en": ["na", ".", ".", "nn", ".", ".", "nd", "nd"],
        "na": [".", ".", ".", ".", ".", ".", ".", "au", ".", ".", "."],
        "wi": ["il"],
        "il": ["ll", "ld", "ld", "ld", "ld", ".", "ld", "la", "ld", ".", "ls", "ld", "lj", "lb", "ly", "ld", "ld", "ld", "ld", "ld", "ld", "ld", "ld"],
        "ll": ["la", "la", "lf", "la", "lv", "la", "lb"],
        "la": [".", "ar", ".", ".", ".", "ag", ".", ".", "au", ".", ".", ".", ".", "au", ".", "."],
        "gw": ["we"],
        "al": ["ld", "ld", "ld", "lv", "ll", "ll", "lf", "ll", "lg"],
        "ld": ["di", ".", "da", "de", "di", ".", "da", "da", ".", ".", ".", "de", ".", ".", "de", ".", ".", "dr", ".", ".", "."],
        "su": ["un"],
        "un": ["nn", ".", "nn", "nn", "nn", ".", "nv", ".", "nn", "nn", "na", "nn", "nn", "nn", "nn", "."],
        "nn": ["ni", "ne", "ne", "na", ".", "na", "nh", "ne", ".", ".", "nr", ".", ".", "."],
        "ni": ["iv", "il", "id"],
        "iv": ["va", "vi", "ve"],
        "va": [".", "al", ".", ".", ".", ".", "an", "ar", "an", "al"],
        "br": ["ry", "ri", "ru", "re"],
        "ry": ["yn"],
        "yn": ["nh", "nn", "."],
        "nh": ["hi", "hi", "hi", "hi", "he"],
        "hi": ["il", "il", "il", "il", "il", "il", "il", "il", "il", "il", "il", "il"],
        "el": ["la", "lg", "li", "lf", "la", "ld", "li", "lk", "ll"],
        "ar": ["ra", "re", "ra", ".", "ri", "rn", "ra", "rn", "rn"],
        "fr": ["re", "ri", "re", "ri", "ri", "ri", "ri", "ru"],
        "re": ["ey", "en", "ef", "ev", "en", "ej", "et", "en", "eg"],
        "ey": ["ya", "yd", "yf"],
        "ya": ["."],
        "da": [".", "ag", ".", "ar", ".", "ag", ".", ".", "al", ".", ".", "ag", "."],
        "in": ["ng", "nn", ".", "ng", ".", "ng", "ne", "nd", "nl", "ng"],
        "ng": ["gr", "ga", "ge", "ge", "gu"],
        "gr": ["ri", "ri", "ru", "re", "ro", "ri"],
        "ri": ["id", "id", "id", "it", "is", "in", "il", "id", "in", "ik", "id", "id", "id", "id", "id", "id", "in", "ig", ".", "im"],
        "id": [".", ".", ".", "dr", "da", ".", ".", "da", ".", ".", "du", ".", "db", "."],
        "ka": ["at", "ar", ".", ".", "at", "at", "."],
        "at": ["tl", "th", "tr", "tl"],
        "tl": ["la", "le", "la"],
        "li": ["in", "it", "iv", "is", "ia", "in"],
        "ne": ["ea", "es", ".", ".", ".", "er", ".", "er"],
        "ea": [".", "."],
        "as": ["st", "st", "sl", "st"],
        "st": ["tr", "ta", "tr", "tv"],
        "tr": ["ri", "ra", "ri", "ri"],
        "si": ["ig", "ig", "ig", "il", "ig"],
        "ig": ["gr", ".", "gn", "gd", ".", "gr", ".", "gg", "gv"],
        "ho": ["or", "or", "or"],
        "or": ["ra", "ru", "ri", "ri", "rh", "rn", ".", "rg", "rd", "rg", "rt", "rd", ".", "rg", "rg", "ra", "rg", "rg", ".", "rd"],
        "yr": ["rs", "ra", "rt"],
        "rs": ["sa", "sa"],
        "sa": [".", ".", ".", ".", ".", ".", "ax", "ag"],
        "ag": ["gn", "gn", "ge", "gn", "gm", "gn", "gn", "ga", "gn", "gn"],
        "gn": ["ny", "na", "nh", "ne", "nf", "ni", "na", "ny", "nh"],
        "ny": [".", ".", "."],
        "ei": ["ir", "ig", "ig", "ig", "ir", "ir", "if", "id"],
        "gu": ["ud", "un", "un", "un", "un", "un"],
        "ud": ["dr", "."],
        "dr": ["ru", "ri", "ri", "."],
        "ru": ["un", "un", "un", "un", "un", "ud", "un"],
        "he": ["el", "er", "ed", ".", "er", "ei"],
        "lg": ["ga", "ge"],
        "ga": [".", ".", "."],
        "is": ["so", ".", "se", ".", ".", ".", "sb", "sa", "sa", ".", ".", ".", ".", "."],
        "so": ["ol", "ol"],
        "ol": ["ld", "lv", "lw", "la", "la", "la", "lb", "lk", "ll", "lo"],
        "de": [".", ".", "."],
        "sv": ["ve", "va"],
        "ve": ["ea", "ei", "ei", "ek", "ei", "ed"],
        "hy": ["yr"],
        "ul": ["ll", "lr", "ld", "lf", "lf"],
        "ae": ["el", "ev", "es"],
        "be": ["er", "et", "er", "er"],
        "er": ["rt", "rd", "rt", "rt", "rg", "ri", "rv", "rd", "rt", "ra", "rd"],
        "rt": ["ta", "th", "th", "tl", "th", "th"],
        "ta": [".", ".", ".", ".", ".", "."],
        "lf": ["fh", "fr", "fh", "fh", "fr"],
        "fh": ["hi", "hi", "hi"],
        "ge": ["er", "er", "eb", "ei", "er", "er"],
        "rd": ["da", "di", "di", "dr", "di", "da"],
        "vi": ["ia", "ig", "iv", "is", "il", ".", "."],
        "ia": [".", "."],
        "ma": ["ar", "ag", "ar", "ae", "at", "ag", "."],
        "es": ["ss", "sa", "st"],
        "ss": ["sa"],
        "pe": ["et"],
        "et": ["tr", "th", "ta"],
        "lv": ["ve", "va", "va", "ve"],
        "to": ["ov", "or", "or"],
        "ov": ["va", "vi"],
        "wy": ["yn"],
        "tt": ["ta", "ta", "ta"],
        "dl": ["ly", "la"],
        "ly": ["yn", "."],
        "fe": ["en"],
        "gi": ["is", "in"],
        "se": ["el", "."],
        "hr": ["re", "ru"],
        "ef": ["fn"],
        "fn": ["na", "."],
        "jo": ["or", "ol", "oh", "ot", "ol", "or", "or", "of", "or", "or", "ot", "or"],
        "ke": ["el", "."],
        "ha": [".", ".", "an", "al", "al"],
        "no": ["or", "or"],
        "lw": ["we"],
        "ev": ["vn", "va"],
        "vn": ["na"],
        "gd": ["di"],
        "wr": ["re"],
        "gm": ["ma"],
        "yd": ["di", "di"],
        "ju": ["ut", "uf"],
        "ut": ["tt"],
        "sb": ["be"],
        "nj": ["jo", "ja"],
        "od": ["di", "di", "dd", "dg"],
        "an": ["nv", "nn", "nd", "nj", "nh"],
        "nv": ["ve", "vo"],
        "rh": ["hi"],
        "lr": ["ri"],
        "ik": ["ka"],
        "ek": ["ka"],
        "yl": ["lv"],
        "bo": ["od", "or", "or"],
        "ce": ["el", "ec"],
        "lk": ["ke", "kv"],
        "ej": ["ja"],
        "ja": [".", ".", "ar", "ar"],
        "dd": ["da", "dn"],
        "ls": ["se"],
        "oh": ["ha"],
        "kj": ["je"],
        "je": ["el", "."],
        "lo": ["ov", "of", "ot", "of"],
        "rn": ["na", "ns", "na", "ng", "nb"],
        "au": ["ug", "ug", "um"],
        "ug": [".", "."],
        "nd": ["di", "dl", "da", "."],
        "lj": ["je", "jo", "ju", "jo"],
        "tu": ["ur"],
        "ur": ["ri", "rs", "ra"],
        "rg": ["gl", ".", ".", ".", "gn", "gu", "."],
        "gl": ["lj"],
        "ot": [".", "th", "tk", "tt", "."],
        "em": ["mb"],
        "mb": ["bl"],
        "bl": ["la"],
        "fj": ["jo"],
        "vo": ["or", "or", "or"],
        "eb": ["bj"],
        "bj": ["jo", "jo", "jo"],
        "ns": ["sa"],
        "ax": ["xa"],
        "xa": ["."],
        "ko": ["ol", "ol"],
        "lb": ["br", "bo", "be"],
        "uf": ["fa"],
        "fa": [".", "as"],
        "my": ["yr"],
        "le": [".", "ei"],
        "oy": ["yd"],
        "nf": ["fr"],
        "sk": ["ku"],
        "ku": ["ul"],
        "sl": ["la"],
        "ec": ["ci"],
        "ci": ["il"],
        "do": ["or", "ot"],
        "fo": ["ol"],
        "kv": ["vi"],
        "oa": ["."],
        "hj": ["jo"],
        "du": ["un"],
        "of": ["fr", "fn", "."],
        "um": ["ma"],
        "dn": ["ny"],
        "ti": ["il"],
        "nr": ["."],
        "bi": ["ir"],
        "cl": ["lo"],
        "gg": ["."],
        "rv": ["vo"],
        "mo": ["od", "or"],
        "dg": ["gu"],
        "hu": ["us"],
        "us": ["."],
        "tk": ["ka"],
        "eg": ["gi"],
        "nl": ["le"],
        "if": ["."],
        "nb": ["bj"],
        "yf": ["fu"],
        "fu": ["ur"],
        "tv": ["vi"],
        "im": ["mh"],
        "mh": ["hi"],
        "kr": ["ra"],
        "ak": ["ka"],
        "db": ["bj"],
        "gv": ["vo"]
      },
      minLen: 3,
      maxLen: 10,
      fallbacks: ["Mira", "Freya", "Astrid"]
    },
    surname: {
      table: {
        "^": ["th", "co", "bl", "as", "wr", "du", "ir", "st", "oa", "ra", "wi", "gr", "ha", "br", "mo", "co", "de", "fa", "go", "he", "ki", "lo", "ni", "ol", "pi", "qu", "re", "si", "ta", "un", "wo", "as", "br", "du", "el", "fo", "gr", "ho", "iv", "ke", "ma", "no", "oa", "pe", "ro", "st", "th", "wh", "ya", "bl", "co", "du", "ea", "fe", "gr", "ha", "ir", "la", "mo", "ni", "ov", "pi", "ra", "sh", "th", "un", "va", "we", "as", "br", "cr", "da", "el", "fr", "gl", "ha", "ir", "je", "ke", "li", "mo", "ne", "oa", "py", "ri", "st", "th", "ul", "va", "wi", "al", "bi", "cl", "de", "ed", "fi", "gl", "hi", "ir", "ju", "kn", "le", "ma", "no", "oa", "ra", "sh", "ta", "up", "va", "wy", "as", "br", "cr", "da", "em", "fe", "gr", "hi", "ir", "ja", "ki", "la", "mi", "no", "oa", "pi", "ro", "st", "tu", "un", "va", "wi", "al", "br", "co", "de", "ev", "fo", "go", "he", "iv", "je", "ke", "lo", "mi", "ne", "ov", "pi", "ro", "si", "th", "um", "va", "wi", "as", "ba", "cl", "da", "ea", "fe", "gi", "he", "in", "ja", "ke", "la", "me", "no", "oa", "pe", "ro", "st", "ta", "ul", "va", "wi"],
        "th": ["ho", ".", "hs", "ho", ".", "hg", "ho", "ho", "ho", "hi", ".", "he", "ho", ".", ".", "hm", "ha", ".", "hw", ".", ".", "ho", "hf", "ho"],
        "ho": ["or", "ol", "or", "ol", "or", "ol", "ol", "or", "ol", "ol", "or", "ol", "ol", "or", "ol", "or"],
        "or": ["rn", ".", "rd", "re", "rt", "rf", "rn", "rt", "rt", "rn", "rn", "re", ".", "rt", ".", "rg", "rm", "rn", "rt", ".", "rn", "rt", "rt", ".", "rt", "rt", ".", "rt", "rt", "re", "rn", ".", "rw", "rn", "."],
        "rn": ["nw", "ne", ".", "nb", ".", "nd", ".", "nf", "ne", "ns", "nw", "nw", "."],
        "nw": ["wo", "wo", "wa", "wi"],
        "wo": ["oo", "or", "ol", "oo", "or", "oo", "oo", "oo", "oo", "or", "oo", "oo", "oo", "or", "oo", "oo", "or", "oo", "oo", "or", "or", "oo", "oo"],
        "oo": ["od", "or", "or", "ok", "od", "ok", "od", "od", "od", "ok", "od", "or", "or", "od", "or", "or", "od", "od", "od", "or", "od", "od", "or", "od", "od", "ok", "or", "od", "or"],
        "od": [".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", "."],
        "co": ["ol", "op", "oa", "oa"],
        "ol": ["ld", "ll", "ld", "ld", "lf", "ll", "ll", "lm", "ll", "lm", "lm", "ll", "ld", "lm"],
        "ld": ["dw", ".", "dl", "dc", "de", ".", ".", ".", "dm", ".", "de", ".", ".", "dg", "dc", ".", ".", "dh", ".", ".", "."],
        "dw": ["we"],
        "we": ["el", "es", "el", "el"],
        "el": ["ll", "lm", "ld", "ld", "ld", "ld", "lm", "ld", "ll", "ld", "ld", "ll", "ld", "ll", "ld", "ll", "lm", "ll", "ld", "ld", "ld", "ld", "ld"],
        "ll": [".", "lo", ".", "lo", ".", "lo", "lo", "lo", ".", ".", ".", ".", ".", "lf", "lo", "lw", "lc", "lh", ".", "ls", "lc", ".", "lo", "lm"],
        "bl": ["la", "la", "le"],
        "la": ["ac", "ac", "ak", "ay", "ar", "ar"],
        "ac": ["ck", "ck", "ck"],
        "ck": ["km", "ks", ".", "kw", "ke", ".", "."],
        "km": ["mo", "me", "mo"],
        "mo": ["oo", "or", "oo", "os", "or", "oo", "oo", "on", "oo", "oo", "oo", "oo", "or", "oo", "oo"],
        "as": ["sh", "st", "sh", "st", "sh", "sh", "st", "sh"],
        "sh": ["hf", "ha", "hw", "ha", "he", "hi", "ha", "hm", "ha", "hd", "hc"],
        "hf": ["fo", "fi"],
        "fo": ["or", "ox", "ox"],
        "rd": [".", "da", "da", ".", "da"],
        "wr": ["re"],
        "re": ["en", ".", "ey", ".", "ed", ".", ".", ".", "ee", ".", ".", ".", "eh", "es", ".", ".", ".", "es", ".", "ey", "es", ".", ".", ".", ".", "es", ".", "es", ".", ".", ".", "es", ".", ".", "es"],
        "en": ["ns", "nc", "nd", "nm", ".", "nh", "ns", "nm", "nd", "nd", "nh", "nm", ".", ".", "nm", ".", "."],
        "ns": ["sh", "sc", "si", "st"],
        "ha": ["aw", "aw", "aw", "av", "aw", "ad", "ar", "ad", "av", "av", "av", "av"],
        "aw": [".", "wk", ".", "wt", "wn"],
        "du": ["un", "us", "un"],
        "un": ["nm", "nd", "nh", "nd", "ni", "nd"],
        "nm": ["mo", "ma", "mo", "mo", "me", "me", "me"],
        "ir": ["ro", "rw", "ro", "ro", "rc", "rs", "ro", "ro"],
        "ro": ["on", "of", "oo", "ov", "oo", "os", "ow", "on", "oo", "os", "on", "of", "on", "on", "os", "of", "of", "oo", "of", "ow", "ow", "of", "os"],
        "on": ["nv", "ne", "ne", "ng", "ne", "nb", "ns", "nd", ".", "ne", "nh", "ne", ".", "ne", "nm", "ne", "ng", "ne"],
        "nv": ["va"],
        "va": ["al", "al", "al", "al", "al", "as", "al", "al", "al"],
        "al": ["le", "ll", "ll", "lb", "le", "le", "le", "ln", "ld", "le", "ll", "le", "ll", "le", "le", "ld", "lh", "le", "le", "le", "lm", "le", "ll", "le"],
        "le": [".", "ea", ".", "ew", ".", ".", "ed", "eb", "ew", "en", "en", ".", "ed", ".", "ew", ".", "ew", ".", ".", "ew", ".", ".", "ec", "em", "em"],
        "st": ["to", "to", "tl", ".", "to", "tm", "tl", "tm", "tf", "to", ".", "to", "to", "to", "th", "to", ".", "te", "ta", "to", "tm", ".", "tm", ".", ".", "to", "."],
        "to": ["on", "on", "on", "or", "on", "on", "on", "on", "on", "on", "on"],
        "ne": ["eh", ".", ".", ".", "eh", ".", "ec", "ew", "et", ".", ".", ".", ".", "ew", ".", "et", "ec", "eb"],
        "eh": ["he", "hu", "hi"],
        "he": ["el", "ea", "en", "er", "ea", "el", "ea"],
        "lm": [".", "me", "me", "ms", ".", "ms", "me", "me", "me"],
        "oa": ["ak", "ak", "al", "ak", "ak", "ak", "al", "ak"],
        "ak": ["kr", "ks", "ke", "kh", "kv", "ke", "kh"],
        "kr": ["ri"],
        "ri": ["id", "ig", "ia", "im", "id", "in", "iv", "id"],
        "id": ["dg", "dg", "de", "ds", "dg"],
        "dg": ["ge", "ge", "ge", "ge", "ga", "ge"],
        "ge": [".", ".", "ew", "ew", "."],
        "ra": ["av", "av", "ag", "av", "ac", "am", "av"],
        "av": ["ve", "ve", "ve", "ve", "ve", "ve", "ve", "ve", "ve"],
        "ve": ["en", "er", "er", ".", ".", "en", "er", "en", "er", "er", "en", "en", "en", "en", "er", "er", "er", "er", "en", "."],
        "nc": ["cr"],
        "cr": ["ro", "ro", "ra", "ro", "re", "re", "re", "ro", "re", "ro", "re", "ro", "re", "ro", "re"],
        "of": ["ft", "ft", "ft", "ft", "ft", "ft"],
        "ft": [".", ".", ".", ".", ".", "."],
        "wi": ["in", "in", "ic", "in", "in", "in", "ic", "il", "ic", "in"],
        "in": ["nt", "nd", "ng", "ne", "ne", "nd", "nw", "nd", "ng", "nd", "ne", "nt", "ne", "nk", "nd"],
        "nt": ["te", "te"],
        "te": ["er", "er", ".", ".", "ec", "er", ".", "ea", "er", ".", "er"],
        "er": ["rb", ".", "rg", "re", ".", "rb", "re", "rh", "rg", "re", ".", "re", "rn", "rd", "re", "rw", "re", "rc", "rb", "rs", "re", "rm", "re", ".", "re", "rt", "re", "rg", "re", "re", "re", "rc", "rf", "re", "rd", "rh", "rv", "rf", "re", "re", "re", "rd", "rn", ".", "re", "re"],
        "rb": ["bo", "br", "be"],
        "bo": ["ou", "or"],
        "ou": ["ur"],
        "ur": ["rn", "rs", "ry", "rn", "rn"],
        "gr": ["re", "ro", "ri", "re", "re", "ra"],
        "ey": ["ym", "ys"],
        "ym": ["ma", "me"],
        "ma": ["an", "ar", "ar", "ar", "ar", "ai"],
        "an": ["ne", "ne"],
        "wk": ["ks"],
        "ks": ["sw", "si", "sh"],
        "sw": ["wo", "wo", "wo", "wo", "wa"],
        "rt": ["th", "th", "th", "th", "th", "tw", ".", "th", "th", "th", "to", "th", "th", "th", "th"],
        "br": ["ri", "ro", "ri", "ro", "ri", "ra", "ra", "ri"],
        "ig": ["gh", "gh", "gh", "gh", "gh"],
        "gh": ["ht", "ht", "ht", "hc", "ht"],
        "ht": ["tw", "tf", "th", "tf"],
        "tw": ["wa", "we"],
        "wa": ["at", "at", "at", "ar", "at", "at"],
        "at": ["te", "te", "te", "te", "te", "tc", "te", "tc", "th", "te"],
        "rf": ["fi", "fe", "fi"],
        "fi": ["ie", "ie", "ie", "ie", "ir", "ie", "ie", "ie", "ie", "ie", "ie", "ie"],
        "ie": ["el", "el", "el", "el", "el", "el", "el", "el", "el", "el", "el", "el"],
        "op": ["pp"],
        "pp": ["pe", "pe"],
        "pe": ["er", "en", "er", "er", "ew"],
        "rg": ["ga", "gr", "ga", "gl"],
        "ga": ["at", "at", "at", "at"],
        "de": ["ee", "er", "er", "er", ".", "er", "ee", "ew", "er", "ew"],
        "ee": ["ep", "en", "ep"],
        "ep": ["ph", "pm"],
        "ph": ["ho"],
        "lo": ["ow", "on", "ow", "ov", "ow", "ow", "ow", "ow", "ow", "on", "ow", "ov"],
        "ow": [".", "wm", "wf", ".", ".", ".", "wm", "wn", ".", ".", "wm", "wm", ".", "wc"],
        "fa": ["ai", "al", "al"],
        "ai": ["ir", "id"],
        "rw": ["wi", "wo", "wo"],
        "nd": [".", "de", ".", "da", "de", "dl", ".", ".", "dm", "da", "dh", ".", "de", "dc"],
        "go": ["ol", "ol"],
        "dl": ["le", "le"],
        "ea": ["af", "ar", "as", "ar", "ad", "ag", "at", "ad"],
        "af": ["."],
        "ar": ["rt", "rk", "rc", "rs", "rk", "rr", "rk", ".", "rc", "rk", "rt", "rt", "rl", "rk", "rk", "rd", "rr", "rk", "rr", "rk"],
        "hs": ["st"],
        "ki": ["in", "in"],
        "ng": ["gs", "gm", "gs", "gd"],
        "gs": ["sm", "sw"],
        "sm": ["ma", "mo"],
        "rk": [".", ".", ".", "kh", "km", "kf", "km", "kf"],
        "gm": ["me", "mo"],
        "me": ["er", "er", "er", "er", ".", "er", ".", "er", "er", "er", "er", "er", "er", "er", "er", "er", "er", "er", "er", ".", "er", "ea", "er"],
        "ni": ["ig", "ig", "ip", "ig"],
        "tf": ["fa", "fi", "fa"],
        "dc": ["ca", "cr", "cr"],
        "ca": ["as", "ar"],
        "tl": ["le", "le", "le", "le", "le"],
        "pi": ["in", "in", "in", "in"],
        "hu": ["ur"],
        "rs": ["st", "sh", "st", "st"],
        "qu": ["ui"],
        "ui": ["ic"],
        "ic": ["ck", "ck", "ck", "ck"],
        "si": ["il", "il", "id", "il"],
        "il": ["lv", "lv", "ll", "ll", "ll", "ll", "ll", "ll", "ll", "lv", "ll", "ld"],
        "lv": ["ve", "ve", "ve", "ve"],
        "ed": ["dt", "do", "dg", "dg"],
        "dt": ["th"],
        "ok": [".", "kh", ".", "kf"],
        "ta": ["al", "al", "ar", "al"],
        "wm": ["me", "me", "me", "me", "me"],
        "rh": ["hi", "hi"],
        "hi": ["il", "ie", "it", "is", "il", "ig", "il", "il", "il"],
        "lf": ["fs", "fi"],
        "fs": ["sb"],
        "sb": ["ba"],
        "ba": ["an", "ar", "ar"],
        "hw": ["wi", "wo", "wi"],
        "ia": ["ar"],
        "rc": ["cl", "ch", "cr", "ch", "cr"],
        "cl": ["li", "li", "la", "li", "lo"],
        "li": ["if", "if", "in", "if"],
        "if": ["ff", "ff", "ff"],
        "ff": [".", ".", "."],
        "us": ["sk"],
        "sk": ["kw"],
        "kw": ["wo", "wa", "wa"],
        "ov": ["ve", "ve", "ve", "ve", "ve"],
        "ox": ["xg", "xw"],
        "xg": ["gl"],
        "gl": ["lo", "le", "le", "lo", "le"],
        "im": ["ms"],
        "ms": ["sh", "sw", "sw"],
        "wf": ["fi", "fi"],
        "iv": ["vy", "ve", "vy"],
        "vy": ["ym", "yw"],
        "ke": ["et", "ew", "el", "en", "en", "el", "et"],
        "et": ["tt", "th", "tt", "tt", "th"],
        "tt": ["tl", "tl", "tl"],
        "ew": ["wo", "wo", "wo", "wo", "wo", "wo", "we", "wo", "wa", "wo", "wo", "wm", "wi", "wf"],
        "no": ["or", "or", "or", "or", "or"],
        "hg": ["ga"],
        "kh": ["ha", "ho", "he", "ha"],
        "ec": ["cr", "cl", "cr", "cr"],
        "os": ["ss", "ss", "st", "se", "se"],
        "ss": [".", "sr"],
        "nb": ["bu", "ba"],
        "bu": ["ur", "ur"],
        "ry": ["."],
        "wh": ["hi"],
        "it": ["te"],
        "ya": ["ar"],
        "rr": ["ro", "ro", "ro"],
        "lb": ["bu"],
        "nh": ["ho", "ho", "ho", "hi"],
        "tm": ["me", "ma", "mo", "mo"],
        "fe": ["er", "el", "el", "er"],
        "da": ["al", "al", "ar", "al", "al", "aw", "al", "al", "al", "ar"],
        "wt": ["th"],
        "sr": ["ri"],
        "sc": ["ca"],
        "ad": ["do", "de", ".", "do"],
        "do": ["ow", "ow", "ow"],
        "is": ["st"],
        "wn": [".", "nm"],
        "eb": ["br", "br"],
        "es": ["st", "sm", "st", "st", "st", "st", "st", "st", "st", "st"],
        "ch": [".", "hw", ".", "."],
        "hm": ["mo", "me"],
        "ag": ["gm", "gl"],
        "fr": ["ro"],
        "je": ["es", "es"],
        "dm": ["me", "me"],
        "py": ["yr"],
        "yr": ["re"],
        "be": ["en", "er", "er"],
        "rm": ["mc", "mo"],
        "mc": ["cr"],
        "nf": ["fi"],
        "ul": ["lv", "lg"],
        "ln": ["no"],
        "bi": ["ir"],
        "ay": ["yb"],
        "yb": ["bo"],
        "pm": ["me"],
        "hc": ["cl", "cr"],
        "ju": ["un"],
        "ip": ["pe"],
        "kn": ["ni"],
        "ds": ["st"],
        "kv": ["va"],
        "up": ["pp"],
        "wy": ["yn"],
        "yn": ["nd"],
        "dh": ["ho", "ho"],
        "hd": ["da"],
        "em": ["mb", "me", "mo"],
        "mb": ["be", "bl", "be"],
        "lw": ["wo"],
        "ys": ["st"],
        "lc": ["cr", "cr"],
        "ja": ["ar", "ar"],
        "rl": ["ls"],
        "ls": ["st", "sw"],
        "mi": ["il", "il"],
        "lh": ["ha", "ha"],
        "tc": ["ch", "ch"],
        "se": ["ew", "et"],
        "kf": ["fi", "fi", "fi"],
        "tu": ["ur"],
        "am": ["mb"],
        "ev": ["ve"],
        "xw": ["wo"],
        "yw": ["wo"],
        "gd": ["da"],
        "rv": ["va"],
        "um": ["mb"],
        "gi": ["il"],
        "nk": ["kw"],
        "wc": ["cr"],
        "lg": ["gr"]
      },
      minLen: 5,
      maxLen: 14,
      fallbacks: ["Thornwood", "Ashford", "Ironvale"]
    }
  },
  elf: {
    name: {
      // Bigram table derived from ~200 curated Elf names
      table: {
        "^": ["li", "ae", "sy", "th", "ca", "ae", "fa", "il", "na", "ve", "ar", "el", "se", "ta", "va", "li", "ni", "fa", "ca", "si", "ae", "so", "th", "ca", "va", "ae", "li", "ni", "el", "sy", "ta", "va", "so", "li", "ni", "ae", "ca", "th", "sy", "va", "ni", "el", "so", "ca", "el", "ti", "va", "fa", "ni", "ta", "ca", "el", "li", "so", "ae", "va", "si", "ni", "el", "ta", "ca", "si", "va", "th", "lo", "ar", "el", "fe", "se", "th", "na", "vo", "il", "sa", "ca", "la", "ae", "th", "va", "na", "so", "fa", "el", "va", "ta", "ni", "ae", "lo", "ca", "sy", "ve", "th", "la", "il", "so", "na", "fa", "ca", "va", "ni", "el", "ta", "so", "ae", "li", "th", "ni", "va", "ca", "fa", "el", "si", "ta", "na", "so", "la", "ae", "ti", "va", "ni", "th", "ca", "fa", "el", "so", "li", "ta", "va", "ae", "ni", "th", "ca", "fa", "si", "el", "ve", "na", "so", "la", "ae", "ti", "va", "ni", "ca", "th", "fa", "el", "so", "ta", "li", "ae", "si", "ni", "va", "th", "ca", "fa", "el", "so", "la", "il", "na", "vo", "ti", "ae", "si", "va", "ni", "ca", "th", "fa", "el", "so", "ta", "li", "ae", "ni", "va", "ca", "th", "fa", "el"],
        "li": ["ir", "io", "in", "ir", "in", "in", "it", "ir", "is", "ir", "it", "in", "io", "in", "it", "in", "ir", "in", "in", "in", "in", "io", "is", "io", "it", "io", "ir", "ir", "is", "ir", "it", "it", "in", "is", "it", "ir", "is", "is", "is", "iv", "ir", "ir", "ir", "ir", "io", "ir", "ir", "io", "it", "it", "it", "ir", "ir", "it", "in", "ir", "ir", "in", "io", "ir", "it", "it", "io", "iv", "ir", "ir", "it"],
        "ir": ["ri", "ri", "ra", "ri", "ri", "ra", "rv", "ri", "ri", "ri", "ri", "rv", "ri", "ri", "re", "ra", "re", "re", "re", "ri", "ra", "re", "ra", "ri", "re", "re", "ri", "re", "re", "ri", "ri", "ri", "re", "ri", "re", "re", "re", "re", "re", "ri", "re", "re", "re", "re", "re", "re", "re", "re", "re"],
        "ri": ["ie", "in", "is", "io", "is", "ie", "is", "ie", "it", "io", "io", "ie", "ie", "it", "it", "is", "io", "io", "is", "in", "ie", "ie", "in", "ie", "ie", "it", "ie", "io", "ie", "io", "ie", "iv", "io", "io", "is", "io", "is", "io", "in", "it", "ie", "in", "ie", "in", "io", "ie", "ie", "in", "iv", "in", "io", "io", "it", "it", "iv", "iv", "ie", "in", "io", "it", "io", "iv", "it", "it", "iv", "it", "iv"],
        "ie": ["en", "el", "el", "en", "en", "el", "en", "el", "el", "en", "en", "en", "en", "el", "en", "en", "en", "en", "el", "el", "el"],
        "en": [".", ".", "na", ".", ".", ".", "na", ".", "ni", ".", "nr", ".", "na", ".", ".", ".", ".", ".", "na", "na", ".", ".", "no", ".", ".", ".", "ni", ".", "ni", ".", ".", ".", ".", "ni", ".", ".", ".", ".", ".", ".", "na", ".", ".", ".", ".", "no", ".", ".", ".", "ni"],
        "ae": ["er", "el", "el", "el", "er", "er", "er", "el", "el", "er", "el", "el", "el", "er", "el", "er", "er", "el", "en", "el", "el", "er", "el", "el", "el", "el", "er", "en", "el", "ev", "er", "er", "el", "el", "er", "el", "en", "el", "el", "el", "el", "el", "er", "el", "er", "er", "el", "er", "et", "el", "er", "er", "el", "er", "er", "er", "el", "el", "el", "er", "el", "er", "el", "el", "el", "ev", "el", "el", "el", "el", "er", "el", "el", "el", "er", "el", "er", "el", "er", "el", "er", "el", "er", "el", "et", "el", "el", "el", "el", "el", "el", "el", "er", "el", "el", "er", "er", "el", "el", "el", "el", "el", "el", "er", "el", "el", "et", "er", "el", "el", "el"],
        "er": ["ri", "ri", "ri", "ri", "ro", "ri", "ri", "ra", "ri", "rl", "ri", "rl", "ra", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ra", "ri", "ri", "ra", "ri", "ri", "re", "ri", "ri", "ra", "ra"],
        "in": [".", "no", "nd", "nd", ".", ".", ".", ".", "nd", "nd", ".", "nd", "nd", "nd", ".", "nd", "nd", "nd", "nd", "nd", "nd", "nd", "nd", "nd"],
        "sy": ["yl", "yl", "yl", "yl"],
        "yl": ["lv", "lv", "lv", "li"],
        "lv": ["va", "ve", "va", "va", "vi", "va", "va", "va", "va", "vi", "va", "vi", "va", "va", "vi", "vi", "vi", "ve", "va", "va"],
        "va": ["ae", "ae", "an", "ae", "ae", "ar", "ae", "ae", "ae", "ae", "ae", "ae", "ar", "ae", "ae", "ae", "ae", "ar", "ae", "al", "ae", "ar", "ae", "al", "ae", "ae", "ae", "ae", "ae", "ae", "an", "ae", "ae", "ae", "al", "al", "ae", "al", "ae", "ae", "ae", "ae", "ae", "al", "ae", "ae"],
        "el": [".", "le", "li", "lo", ".", "la", "lu", "la", ".", ".", "la", "li", ".", "li", "la", "li", ".", ".", "li", "li", "li", "la", ".", "la", "li", "li", "li", ".", "la", "li", "li", ".", ".", "li", ".", "lv", ".", "li", "lo", "li", "lv", "li", "li", "li", ".", ".", "la", "li", "li", "lo", "li", "li", "li", "lv", "la", ".", "li", "li", "li", ".", "li", ".", ".", ".", "li", "la", ".", ".", "li", "li", ".", "li", ".", "lo", "la", ".", "li", ".", ".", "li", "li", "li", "la", "li", "li", "li", "li", "li", "li", "lo", ".", ".", "li", "li", "li", "li", "lv", ".", "li", ".", "lo", ".", "li", ".", "li", ".", "li", "la", "."],
        "th": ["ha", "ha", ".", ".", ".", ".", "ha", ".", ".", "he", "ha", ".", "hi", ".", "hi", "he", ".", ".", ".", "hi", "ha", "he", ".", "ha", "he", ".", "hi", "he", "he", "he", "he", "he", "hi", "ha", "he", "he", "hr", "he", "ha", "hr", "hi", "he", "hr"],
        "ha": ["al", "al", "ae", "ar", "ae", "al", "ae", "ae"],
        "al": ["li", "li", ".", "li", "li", ".", "li", "li", ".", ".", ".", ".", "."],
        "io": ["on", "on", "on", "on", "on", "on", "on", "on", "on", "on", "on", "on", "on", "on", "on", "on", "on", "on", "on", "on", "on", "on", "on", "on", "on", "on", "on", "on", "on", "on", "on", "on", "on", "on"],
        "on": [".", ".", ".", ".", ".", ".", ".", ".", ".", ".", "ni", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", "."],
        "ca": ["ae", "ae", "ae", "ae", "ae", "ae", "ae", "ae", "ae", "ae", "ae", "ae", "ae", "ae", "ae", "ae", "ae"],
        "le": ["en", "en"],
        "no": ["or", "or", "or"],
        "or": [".", "ri", "rv", "ra", "rv", "ri", "ri", "re", "ri", "re", "ri", "rv", ".", "ri", "re", "ri", "re", "ri", "re", "ri", ".", "ri"],
        "fa": ["ae", "ae", "ae", "ae", "ae", "ae", "ae", "ae", "ae", "ae", "ae", "ae"],
        "is": [".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", "."],
        "il": ["lv", ".", "lv", "lv", "lv", "le", "lv", "lv", "lv", "lv", "lv", "lv"],
        "ve": ["en", "el", "el", "el", "el", "en", "el", "el", "el"],
        "na": ["ai", "ae", "ar", "ae", "ar", "ae", "ar", "al", "ae", "ae", "ae", "al", "ae"],
        "ai": ["."],
        "lo": ["or", "or", "on", "or", "or", "or", "or", "or"],
        "ar": ["ri", "ri", "ra", "ri", ".", ".", "ra", "ri", "ri", ".", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri"],
        "la": ["an", "an", "an", "ar", "av", "ar", "an", "ae", "ar", "ae", "ar", "ae", "ar", "ar", "ae", "ar", "ae", "ar"],
        "an": ["ni", ".", ".", ".", "ni", ".", "ni"],
        "ni": ["il", "ir", "ir", "ir", "ir", "ir", "ir", "is", "ie", "is", "ir", "ir", "ir", "ir", "ir", "it", "ir", "ie", "ir", "ir", "ir", "ir", "ir", "iv"],
        "se": ["el", "el"],
        "lu": ["un"],
        "un": ["ne"],
        "ne": ["."],
        "ta": ["ae", "ae", "ae", "ae", "ae", "ae", "ae", "ae", "ae", "ae"],
        "ra": ["ae", ".", ".", ".", "al", "ae", "ae", ".", ".", ".", "an", ".", ".", "av", "al", ".", ".", ".", ".", "ae", "ae", "ae", ".", ".", "av", ".", ".", ".", ".", "av", ".", "av", "."],
        "ro": ["on"],
        "si": ["il", "il", "il", "il", "il", "il", "il"],
        "nd": ["dr", "dr", "dr", "dr", "dr", "dr", "dr", "dr", "dr", "dr", "dr", "dr", "dr", "dr", "dr", "dr"],
        "dr": ["ra", "ra", "ra", "ra", "ra", "ra", "ra", "ra", "ra", "ra", "ra", "ra", "ra", "ra", "ra", "ra"],
        "so": ["or", "or", "ol", "or", "or", "or", "or", "or", "or", "or", "ol", "or", "ol"],
        "rv": ["va", "va", "vi", "va", "va"],
        "it": ["th", "th", "th", "th", "th", "th", "th", "th", "th", "th", "th", "th", "th", "th", "th", "th", "th", "th", "th", "th", "th", "th", "th", "th", "th", "th"],
        "vi": ["io", "in", "in", "io", "io", "io", "io", "io", "ir", "ir", "ir", "io", "io"],
        "av": ["vi", "va", "ve", "ve", "ve"],
        "ol": ["lv", "lv", "lv"],
        "rl": ["li", "li"],
        "ti": ["ir", "ir", "ir", "ir"],
        "ev": ["vi", "vi", "va", "va", "va", "va", "vi", "va"],
        "he": ["en", "en", "en", "en", "en", "en", "en", "en", "en", "en", "en", "en", "en"],
        "fe": ["en"],
        "nr": ["ri"],
        "vo": ["or", "or"],
        "sa": ["ae"],
        "hi": ["ir", "ie", "ie", "ir", "io", "ir"],
        "re": ["el", "en", "en", "en", "el", "en", "en", "en", "en", "ev", "el", "en", "el", "ev", "en", "en", "ev", "en", "el", "en", "ev", "en", "en", "el", "en", "el", "ev", "en", "ev", "en"],
        "et": ["th", "th", "th"],
        "iv": ["va", "vi", "va", "va", "va", "va", "va", "vi", "va", "ve"],
        "hr": ["ra", "ra", "ra"]
      },
      minLen: 4,
      maxLen: 12,
      fallbacks: ["Lirien", "Aerin", "Thalion", "Aelinor", "Vaelith"]
    }
  },
  dwarf: {
    name: {
      // Bigram table derived from ~200 curated Dwarf personal names
      table: {
        "^": ["th", "gi", "ba", "dw", "oi", "gl", "bi", "bo", "bo", "no", "do", "or", "th", "fu", "gr", "na", "da", "fr", "gr", "bo", "fa", "lo", "fr", "fl", "na", "an", "or", "ut", "ig", "al", "ed", "ul", "ar", "ok", "ur", "an", "al", "un", "ig", "or", "ul", "ar", "ed", "ok", "ur", "an", "al", "ur", "ig", "or", "ul", "ar", "ed", "ok", "ur", "an", "al", "un", "ig", "or", "ul", "ar", "ed", "ur", "br", "du", "th", "gr", "gr", "kh", "dr", "br", "th", "gr", "br", "kh", "du", "br", "gr", "th", "br", "dr", "kh", "gr", "th", "dr", "gr", "br", "dr", "gr", "th", "br", "kh", "gr", "du", "br", "gr", "th", "br", "kh", "gr", "dr", "br", "gr", "th", "br", "kh", "dr", "gr", "br", "du", "gr", "th", "br", "kh", "gr", "dr", "gr", "th", "br", "du", "gr", "th", "kh", "dr", "gr", "br", "gr", "th", "br", "kh", "dr", "gr", "th", "br", "kh", "gr", "dr", "br", "gr", "th", "br", "kh", "dr", "gr", "th", "br", "kh", "gr", "dr", "gr", "br", "gr", "bo", "th", "gr", "du", "kh", "br", "gr", "th", "br", "kh", "dr", "gr", "br", "du", "gr", "th", "br", "kh", "gr", "dr", "gr", "th", "br", "du", "gr", "th", "br", "kh", "dr", "gr"],
        "th": ["ho", "hr", "he", ".", ".", "ho", "ho", ".", "ho", "ho", "ho", ".", "ho", "ho", ".", "ho", "ho", ".", "ho", ".", "ho", ".", "hu", ".", ".", ".", "ho", ".", "ho", ".", ".", ".", "ha", "ho", ".", "hu", ".", "ho", "ho", ".", "."],
        "ho": ["or", "or", "or", "or", "or", "or", "or", "or", "or", "or", "or", "or", "or", "or", "or", "or", "or", "or", "or", "or", "or", "or", "or", "or", "or", "or", "or"],
        "or": ["ri", "ri", "ri", "ri", ".", ".", "ri", "ri", ".", "rv", "rm", ".", "rk", "rd", "rd", ".", "rb", "rg", "rn", "rn", ".", "rb", "rg", "rg", ".", "rn", "rv", "rd", "rg", "rn", "rb", ".", "rn", "rv", "rn", "rb", "rg", ".", "rk", "rn", ".", "rv", "rd", ".", "rn", "rb", "rv"],
        "ri": ["in", ".", ".", ".", "in", "in", "in", "ik", "im", "ic", "in", "ik", "ic", "im", "im", "im", "im", "im", "im", "im", "im", "in", "im", "im", "im", "in", "im", "im", "im", "im", "in", "im", "im", "im", "im", "im", "in", "im", "im", "im", "im", "im"],
        "in": [".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", "nd", ".", "nd", "nd", "nd"],
        "gi": ["im", "in", "in"],
        "im": ["ml", ".", ".", ".", ".", ".", ".", ".", ".", "mn", ".", "mg", "mv", ".", ".", ".", "mn", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", "mv", "."],
        "ml": ["li"],
        "li": [".", "in", "in"],
        "ba": ["al", "ar", "ar", "ar", "ar", "ar", "ak", "ar", "ar", "ar", "ar", "ak", "ar", "ar", "ar"],
        "al": ["li", "li", "ld", "lr", "ld", "ld", "ld", "lb", "ld", "ld", "ld", "ld", "ld", "ld", "ld", "ld", "ld", "ld", "ld", "ld", "ld", "lg", "ld", "ld", "ld"],
        "dw": ["wa"],
        "wa": ["al"],
        "oi": ["in", "in", "."],
        "gl": ["lo"],
        "lo": ["oi", "on", "oi"],
        "bi": ["if", "in"],
        "if": ["fu"],
        "fu": ["ur", "ur", "un"],
        "ur": [".", ".", ".", ".", "rg", "rg", ".", "ra", "rg", ".", "rv", "rg", ".", ".", "rg", ".", ".", "rd", ".", "rn", "rn", "rn", ".", "rn", ".", "rd", "rd", "rn", ".", ".", "rg", "rv", "rb", "rn", "rn", ".", ".", "rv"],
        "bo": ["of", "om", "or", "or"],
        "of": ["fu"],
        "om": ["mb", "mn", "mb", "mg", "mn", "mv", "mr", "mn"],
        "mb": ["bu", "ba", "ba"],
        "bu": ["ur", "ur", "ur"],
        "no": ["or", "or", "or", "ok", "ok", "ok", "or", "ok", "ok", "ok", "ok", "ok", "or", "ok", "ok", "or"],
        "do": ["or", "or", "or", "or", "or"],
        "hr": ["ra"],
        "ra": ["ai", "ak", "ak", "ak", "ak", "ag", "ag", "ak", "ag", "ak", "av", "ak", "ag", "ak", "ag"],
        "ai": ["in", "in", "in"],
        "un": ["nd", "nd", "nd", "nd", "nd", "nd", "ng", "nn", "nd", "nd", "nv", ".", "nd", "na", "nd", "no", "nd", "nn"],
        "nd": ["di", ".", "da", ".", "do", "da", "du", "di", "da", "do", "da", "dr", "du", "di", "du", "do", "di", "da"],
        "di": ["in", "im", "ir", "im", "im", "im"],
        "gr": ["ro", "ru", "ri", "ri", "ri", "ri", "ri", "ra", "ri", "ri", "ro", "ri", "ro", "ro", "ri", "ri", "ro", "ra", "ri", "ro", "ro", "ri", "ri", "ro", "ra", "ro", "ri", "ri", "ro", "ra", "ri", "ro", "ri", "ro", "ri", "ri", "ra", "ro", "ri", "ri", "ru", "ro", "ro", "ra", "ri", "ro", "ro", "ro"],
        "ro": ["or", "or", "ok", "og", "on", "og", "om", "om", "og", "on", "ok", "om", "ok", "on", "om", "og", "ok", "ok", "on", "om", "on", "og", "og", "on", "om", "on", "ok", "om"],
        "na": ["ai", "ar", "ar", "ar", "ak", "ar", "ar", "ar", "ar", "ak", "ar", "ar", "ak", "ar", "ak", "ar", "ak", "at", "at", "at", "at", "at", "at", "at", "at", "ar", "at", "ak", "at", "at", "at"],
        "da": ["ai", "ak", "ar", "ak", "ak", "ak", "ak", "ak", "ak", "ak"],
        "fr": ["ro", "re", "ri"],
        "ru": ["ur", "um", "un", "un", "ug", "un", "ug", "un", "un", "um", "un", "ug", "un", "ug", "uk", "uk", "un", "um", "ug", "un", "uk", "uk", "un", "ug", "un", "ug", "un", "uv"],
        "fa": ["ar"],
        "ar": ["ri", ".", ".", ".", "rm", ".", ".", "rg", ".", ".", ".", "rn", ".", ".", "rb", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", "."],
        "on": ["ni", "nn", "nd", "nd", "na", "nn", "nd", "nn"],
        "ni": ["."],
        "re": ["er"],
        "er": ["ri", "."],
        "fl": ["lo"],
        "an": ["na", "ng", "nk", "ng", "."],
        "ik": [".", "."],
        "ut": ["th"],
        "he": ["er"],
        "ig": ["gr", "gn", "gb", "gv"],
        "ld": ["do", ".", "dr", "da", ".", ".", "dr", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", "."],
        "ed": ["dr", "dg", "dv", "dn"],
        "dr": ["ri", "ri", "ri", "ru", "ra", "ro", "ru", "ru", "ra", "ri", "ra", "ri", "ru", "ra", "ru", "ra", "ru", "ra", "ra", "ru"],
        "ic": [".", "."],
        "ul": ["lg", "lf", "ld", "ld"],
        "lg": ["ga", "gr"],
        "ga": ["ar", "at", "ar", "ar", "at", "ar", "an", "at", "ar", "at", "ar", "at"],
        "rm": ["mu", "mu"],
        "mu": ["un", "un"],
        "ok": ["kr", "kb", "kr", "ka", ".", ".", "kn", "kb", ".", ".", ".", "kv", "kd", ".", ".", ".", ".", ".", ".", ".", "kr", "."],
        "kr": ["ri", "ri", "ri", "ri"],
        "rg": ["ga", "gi", "gr", "gn", "gr", "gi", "ga", "ga", "ga", "gr", "gr", "gr"],
        "at": ["th", "th", "th", "th", "th", "th", "th", "th", "th", "th", "th", "th", "th", "th", "th", "th", "th", "th", "th"],
        "ng": ["ga", "gr", "ga", "ga"],
        "lr": ["ri"],
        "ak": [".", ".", ".", ".", "ku", ".", ".", "ku", ".", ".", ".", ".", "kb", ".", ".", ".", "kd", ".", "kg", "kn", ".", ".", "kr", "."],
        "gn": ["na", "na", "na", "na", "no", "na", "no", "na", "no", "no", "na", "no"],
        "rv": ["va", "va", "va", "va", "va", "va", "vo", "vo"],
        "va": ["al", "al", "al", "al", "al", "al", "al", "al", "al", "al", "al", "al", "al", "al", "al", "al", "al", "al"],
        "lf": ["fr"],
        "dg": ["gr"],
        "kb": ["ba", "ba", "ba"],
        "nk": ["ku"],
        "ku": ["ur", "ur", "ur", "ur"],
        "gb": ["ba", "ba"],
        "rn": ["na", "nu", "nb", "no", "no", "na", "ng", "nv", "nv", "no", "na", "na", "no", "na", "no", "nb"],
        "dv": ["va"],
        "lb": ["ba"],
        "gv": ["va", "va"],
        "rk": ["ku", "ka"],
        "rb": ["ba", "bi", "ba", "bu", "ba", "ba", "ba"],
        "dn": ["na"],
        "br": ["ro", "ru", "ru", "ro", "ru", "ru", "ru", "ro", "ru", "ro", "ru", "ru", "ru", "ru", "ro", "ru", "ru", "ro", "ru", "ru", "ro", "ro", "ru", "ru", "ru", "ru", "ru"],
        "ka": ["at", "at"],
        "du": ["ur", "ur", "ur", "ur", "ur", "un", "ur", "ur", "ur", "ur", "ur", "ur", "ur", "ur", "ur"],
        "rd": ["da", "di", "da", "du", "dr", "da", "du"],
        "mn": ["na", "no", "na", "na", "no", "na"],
        "kh": ["ho", "ho", "hu", "ho", "hu", "ho", "ho", "hu", "ho", "hu", "ho", "hu", "ho", "hu", "ho", "ho"],
        "um": ["mn", "mv", "mb"],
        "og": ["gn", "gn", "gr", "gn", "gn", "gn"],
        "nn": ["na", "na", "no", "na", "na"],
        "nu": ["ur"],
        "ug": ["gn", "ga", "gv", "ga", "gr", "gb", "gd"],
        "hu": ["ur", "ur", "ur", "ur", "ur", "ur", "ur", "ur"],
        "mg": ["ga", "ga"],
        "nb": ["bu", "ba"],
        "ir": ["."],
        "mv": ["va", "va", "va", "vo"],
        "kn": ["na", "no", "na", "na", "na", "na"],
        "nv": ["va", "va", "va"],
        "ag": ["gn", "gn", "gr", "gn", "gn"],
        "kd": ["di", "du"],
        "uk": ["kn", "kn", "kn", "kn"],
        "kv": ["va"],
        "kg": ["gr"],
        "av": ["va"],
        "ha": ["al"],
        "mr": ["ri"],
        "vo": ["ok", "ok", "ok"],
        "gd": ["du"],
        "uv": ["va"]
      },
      minLen: 3,
      maxLen: 9,
      fallbacks: ["Thorin", "Brokath", "Grimnar", "Aldrim", "Urgath"]
    },
    clan: {
      // Bigram table derived from ~200 curated Dwarf clan names
      table: {
        "^": ["ir", "st", "gr", "bo", "an", "fo", "st", "co", "ir", "st", "gr", "bo", "an", "st", "ir", "st", "gr", "an", "st", "co", "ir", "st", "gr", "bo", "fo", "st", "co", "ir", "st", "gr", "bo", "an", "st", "co", "ir", "st", "gr", "bo", "fo", "st", "co", "ir", "st", "gr", "bo", "an", "st", "co", "ir", "st", "gr", "bo", "fo", "st", "co", "ir", "gr", "bo", "an", "st", "co", "ir", "st", "gr", "bo", "an", "st", "co", "ir", "st", "gr", "bo", "an", "fo", "st", "co", "ir", "st", "gr", "bo", "an", "fo", "st", "co", "ir", "st", "gr", "bo", "an", "fo", "st", "co", "ir", "st", "gr", "bo", "an", "fo", "st", "co", "br", "br", "br", "br", "br", "br", "si", "si", "si", "si", "si", "si", "go", "go", "go", "go", "go", "go", "fl", "fl", "fl", "fl", "fl", "fl", "sl", "sl", "sl", "sl", "sl", "sl", "gr", "gr", "gr", "gr", "gr", "gr", "ha", "ha", "ha", "ha", "ha", "ha", "ax", "ax", "ax", "ax", "ax", "ax", "sh", "sh", "sh", "sh", "sh", "sh", "he", "he", "he", "he", "he", "he", "de", "de", "de", "de", "de", "de", "un", "un", "un", "un", "un", "un", "da", "da", "da", "da", "da", "da", "bl", "bl", "bl", "bl", "bl", "bl", "re", "re", "re", "re", "re", "re", "as", "as", "as", "as", "as", "as", "ru", "ru", "ru", "ru", "ru", "ru"],
        "ir": ["ro", "ro", "ro", "ro", "ro", "ro", "ro", "ro", "ro", "ro", "ro", "ro", "ro", "ro"],
        "ro": ["on", "ow", "on", "ow", "on", "ow", "on", "on", "on", "on", "on", "on", "on", "on", "on", "on", "on", "on", "on", "on", "on", "on", "on"],
        "on": ["nm", "ne", "nb", "ne", "nf", "ne", "ng", "ne", "nb", "ne", "nh", "ne", "nh", "ne", "nw", "ne", "ns", "ne", "ne", "ne", "ne", "ne", "ne", "nf", "ne", "nb", "ne", "nd", "ne", "nc", "ne", "nw", "ne", "nz", "nz", "nz", "nz", "nz", "nz", "ne"],
        "nm": ["ma"],
        "ma": ["an", "an", "an", "an", "an", "an", "an", "an", "an"],
        "an": ["nt", "nv", "nv", "nv", "nd", "nd", "nd", "nd", "nv", "nd", "nd", "nd", "nv", "nv", "nv", "nv", "nv", "nv", "nv", "nt", "nt", "nt", "nt", "ni", "ni", "ni", "ni", "ni", "ni", "nd", "nt", "nt", "nt", "nt"],
        "nt": ["tl", "tl", "tl", "tb", "tg", "th", "th", "tm", "tl", "tb", "tl", "tl", "tl", "tl", "tl"],
        "tl": ["le", "le", "le", "le", "le", "le", "le", "le", "le"],
        "le": [".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", "."],
        "st": ["to", "te", "to", "te", "to", "te", "to", "te", "to", "te", "to", "te", "to", "te", "to", "te", "to", "to", "to", "to", "te", "to", "to", ".", "to", ".", ".", ".", ".", "te", ".", ".", "to", "te", "to", "te", ".", "to", ".", ".", ".", ".", ".", "te", ".", ".", "to", "te", ".", ".", ".", ".", ".", "to", ".", ".", ".", ".", "tm", "tg", "th", "th", "tb", "tw"],
        "to": ["on", "on", "on", "on", "on", "on", "on", "on", "on", "on", "on", "on", "on", "on", "on", "on", "on", "on", "on", "on"],
        "ne": ["eb", "eh", "eb", "eg", "eb", "eh", "eh", "ew", ".", ".", ".", ".", ".", ".", "ef", "eb", "ed", "ec", "ew", "."],
        "eb": ["ba", "br", "br", "bo", "bo", "ba", "bo", "bo", "bo", "br"],
        "ba": ["ac", "ac", "ac", "ac", "ac"],
        "ac": ["ck", "ck", "ck", "ck", "ck", "ck", "ck", "ck", "ck", "ck", "ck"],
        "ck": [".", ".", ".", ".", ".", "km", "kg", "kh", "kh", "kb", "kw"],
        "gr": ["re", "re", "re", "re", "re", "re", "re", "re", "re", "re", "re", "re", "re", "re", "ra", "ra", "ra", "ra", "ra", "ra"],
        "re": ["ey", "ey", "ey", "ey", "ey", "ey", "ey", "ey", "ey", "ey", "ey", "ey", "es", "es", "ey", "es", "es", "es", "es", "es", "es", "ey", "es", "es", "es", "es", "es", "ed", "ed", "ed", "ed", "ed", "ed", "es", "es"],
        "ey": ["yh", "yb", "yk", "yg", "yb", "yh", "yh", "yw", "ys", "yf", "yb", "yd", "yc", "yw"],
        "yh": ["ho", "he", "he"],
        "ho": ["ol", "ol", "ol", "ol", "ol", "ol", "ol", "ol"],
        "ol": ["ld", "ld", "ld", "ld", "ld", "ld", "ld", "ld", "ld", "ld", "ld", "ld", "ld", "ld"],
        "ld": [".", "de", ".", "de", ".", ".", "de", "de", "de", "de", "de", "de", "de", "de", "de", "da", "da", "de", "de", "dc", "dm", "dg", "dh", "dh", "dw", ".", "db", "dg", "dh", "dh", "db", "dw", ".", ".", "."],
        "bo": ["ou", "ou", "ou", "ou", "ou", "ou", "ou", "ou", "ou", "or", "or", "or", "ou", "or", "or", "or", "or", "or", "ou", "ou", "ou", "or", "or", "or", "or", "or", "or", "or", "or", "or", "or", "or", "or", "or", "or", "or"],
        "ou": ["ul", "ul", "ul", "ul", "ul", "ul", "ul", "ul", "ul", "ul", "ul", "ul", "ul"],
        "ul": ["ld", "ld", "ld", "ld", "ld", "ld", "ld", "ld", "ld", "ld", "ld", "ld", "ld"],
        "de": ["er", "er", "er", "er", "er", "er", "er", "er", "er", "er", "er", "er", "er", "ee", "ee", "ee", "ee", "ee", "ee", "er", "er", "er", "er", "er", "er"],
        "er": ["rk", "rv", "rf", "rh", "rg", "rg", "rb", "rb", "rh", "rh", "rh", "rh", "rw", "rw", "rs", "rs", "rf", "rf", "rb", "rb", "rd", "rd", "rc", "rc", "rw", "rw", "rv", "rf", "rg", "rh", "rh", "rb", "rf", "rf", "rg", "rh", "rh", "rb", "rh", "rg", "rh", "rh", "rb", "rw"],
        "rk": ["ki", "kh", "kg", "kh", "kh", "kb", "kc"],
        "ki": ["in", "in", "in"],
        "in": [".", ".", ".", ".", ".", "nt", "nt", "nt", "nt", "nt", "nt"],
        "nv": ["vi", "vi", "vi", "vi", "vi", "vi", "vi", "vi", "vi", "vi", "vi"],
        "vi": ["il", "il", "il", "il", "il", "il", "if", "il", "il", "il", "il"],
        "il": ["lf", "lp", "lh", "lb", "lh", "ls", "lb", "ld", "lc", "lw", "lv", "lv", "lv", "lv", "lv", "lv"],
        "lf": ["fo", "fi"],
        "fo": ["or", "or", "or", "or", "or", "or", "or", "or", "or", "or", "or"],
        "or": ["rg", "rg", "rg", "rg", "rg", "rg", "rg", "rn", "rn", "rn", "rn", "rn", "rg", "rn", "rn", "rn", "rg", "rg", "rg", "rn", "rn", "rn", "rn", "rn", "rn", "rn", "rn", "rn", "rn", "rn", "rn", "rn", "rn", "rn"],
        "rg": ["ge", "ge", "ge", "ge", "gu", "ge", "gu", "ge", "ge", "ge", "ge", "ge", "ge", "gu", "gu", "gu"],
        "ge": [".", "ep", ".", ".", "eg", "eh", "ew", "eb", "ed", "ec", "ew"],
        "ep": ["pe", "ph", "pg", "ph", "ph", "pb", "pc"],
        "pe": ["ea", "er", "ea", "ea", "er", "er", "er", "er", "er", "er", "er", "er", "er", "er", "er", "er"],
        "ea": ["ak", "ak", "ak", "ar", "ar", "ar", "ar", "ar", "ar", "ar", "ar", "ar", "ar", "ar", "ar", "ar", "ar", "ar", "ar", "ar", "ar", "ar", "ar", "ar", "ar", "ar", "ar"],
        "ak": [".", ".", "."],
        "te": ["ee", "ee", "ee", "ee", "ee", "ee", "ee", "ee", "ee", "ee", "ee", "ee", "ee", "ee", "eg", "eh", "eh", "eb", "ec", "em", "eh", "eg", "eh", "eh", "eb", "ew"],
        "ee": ["el", "el", "el", "el", "el", "el", "el", "el", "el", "el", "el", "el", "el", "el", "ep", "ep", "ep", "ep", "ep", "ep"],
        "el": ["lb", "lk", "lp", "lg", "lb", "lh", "lm", "lm", "lm", "lm", "lm", "lh", "lm", "lm", "lw", "ls", "lf", "lb", "ld", "lc", "lw", "lm", "lm", "lm", "lm", "lm", "lm", "lm", "lm", "ld", "ld", "ld", "ld", "lm", "ld", "ld", "lm", "lm", "lm", "lm", "lm", "lm", "lm", "lm", "lm", "lm", "lm", "lm", "lm"],
        "lb": ["br", "br", "br", "bo", "bo"],
        "br": ["ro", "ro", "ro", "ra", "ra", "ra", "ra", "ra", "ra", "ra", "ro", "ro", "ro", "ro", "ro", "ro", "ra"],
        "ow": [".", ".", "."],
        "co": ["op", "op", "op", "op", "op", "op", "op", "op", "op", "op", "op", "op", "op"],
        "op": ["pp", "pp", "pp", "pp", "pp", "pp", "pp", "pp", "pp", "pp", "pp", "pp", "pp"],
        "pp": ["pe", "pe", "pe", "pe", "pe", "pe", "pe", "pe", "pe", "pe", "pe", "pe", "pe"],
        "rv": ["ve", "ve"],
        "ve": ["ei", "er", "ei", "er", "er", "er", "er", "er"],
        "ei": ["in", "in"],
        "nb": ["ba", "br", "bo"],
        "eh": ["ho", "he", "he", "he", "he", "he", "he", "he", "ho", "he", "he", "he", "he"],
        "yb": ["br", "br", "bo"],
        "rf": ["fo", "fi", "fi", "fi", "fa", "fi"],
        "lp": ["pe", "pe"],
        "lk": ["ki"],
        "nf": ["fo", "fi"],
        "yk": ["ki"],
        "lh": ["ho", "he", "he", "he"],
        "rh": ["ho", "he", "he", "he", "he", "he", "he", "he", "he", "ho", "he", "he"],
        "ng": ["gu"],
        "gu": ["ua", "ua", "ua", "ua", "ua", "ua", "ua", "ua", "ua", "ua", "ua", "ua", "ua", "ua", "ua", "ua", "ua", "ua", "ua", "ua", "ua", "ua", "ua", "ua"],
        "ua": ["ar", "ar", "ar", "ar", "ar", "ar", "ar", "ar", "ar", "ar", "ar", "ar", "ar", "ar", "ar", "ar", "ar", "ar", "ar", "ar", "ar", "ar", "ar", "ar"],
        "ar": ["rd", "rd", "rd", "rd", "rd", "rd", "rd", "rt", "rt", "rt", "rt", "rt", "rt", "rt", "rd", "rd", "rd", "rd", "rd", "rd", "rd", "rd", "rd", "rt", "rd", "rd", "rt", "rd", "rt", "rd", "rd", "rt", "rd", "rt", "rd", "rt", "rd", "rt", "rd", "rt", "rd", "rd", "rt", "rd", "rt", "rd", "rd", "rt", "rd", "rt", "rk", "rk", "rd", "rk", "rt", "rk", "rk", "rk", "rd", "rt", "rd", "rt", "rd", "rt", "rd", "rt", "rd"],
        "rd": [".", ".", ".", ".", ".", ".", ".", "da", "da", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", "."],
        "eg": ["gu", "gu", "gu", "gu", "gu", "gu"],
        "yg": ["gu"],
        "lg": ["gu"],
        "ra": ["an", "an", "an", "an", "an", "an", "an", "an", "an", "an", "an", "an", "an", "an"],
        "nd": [".", ".", ".", ".", ".", ".", ".", "da", ".", "de", "de", "de", "de", "de", "de"],
        "rb": ["br", "br", "bo", "bo", "bo", "bo", "bo"],
        "nh": ["he", "he"],
        "he": ["ea", "ea", "ea", "ea", "ea", "ea", "ea", "el", "el", "el", "el", "el", "el", "el", "ea", "el", "ea", "el", "ea", "el", "ea", "el", "ea", "el", "ea", "el", "ea", "el", "ea", "el", "ea", "el", "el", "el", "ea", "el", "el", "el", "el", "ea", "el", "ea", "el", "ea", "el", "ea", "el", "ea", "el", "ea", "el", "ea", "el"],
        "rt": [".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", "."],
        "lm": [".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", "mg", "mh", "mb", "mw", "mc", "ms", ".", ".", ".", ".", ".", ".", "."],
        "nw": ["wa", "wa"],
        "wa": ["al", "al", "al", "al", "al", "al", "al", "ar", "ar", "ar", "ar", "ar", "ar", "ar", "ar", "ar", "ar", "al", "ar", "al", "ar", "al", "al", "ar"],
        "al": ["ll", "ll", "ll", "ll", "ll", "ll", "ll", "le", "le", "le", "le", "le", "le", "le", "le", "ll", "ll", "ll", "ll", "ll"],
        "ll": [".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", "."],
        "ew": ["wa", "wa", "wa", "wa", "wa", "wa", "wa"],
        "yw": ["wa", "wa"],
        "rw": ["wa", "wa", "wa", "wa", "wa"],
        "lw": ["wa", "wa", "wa"],
        "ns": ["st"],
        "ys": ["st"],
        "rs": ["st", "st"],
        "ls": ["st", "st"],
        "fi": ["is", "is", "is", "is", "is", "is", "is", "is", "is"],
        "is": ["st", "st", "st", "st", "st", "st", "st", "st", "st"],
        "ef": ["fi"],
        "yf": ["fi"],
        "if": ["fi"],
        "rn": [".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", "."],
        "da": ["al", "al", "al", "al", "al", "al", "al", "al", "ar", "ar", "ar", "ar", "ar", "ar"],
        "ed": ["da", "da", "dm", "dg", "dh", "dh", "db", "dc"],
        "yd": ["da"],
        "nc": ["cr"],
        "cr": ["re", "re", "re", "re", "re", "re", "re", "re", "re", "re", "re", "re", "re", "re", "re"],
        "es": ["st", "st", "st", "st", "st", "st", "st", "st", "st", "st", "st", "st", "st", "st", "st"],
        "ec": ["cr", "cr", "cr"],
        "yc": ["cr"],
        "rc": ["cr", "cr"],
        "lc": ["cr", "cr"],
        "nz": ["ze", "ze", "ze", "ze", "ze", "ze"],
        "ze": ["eb", "eg", "eh", "eh", "em", "ew"],
        "em": ["ma", "ma"],
        "si": ["il", "il", "il", "il", "il", "il"],
        "lv": ["ve", "ve", "ve", "ve", "ve", "ve"],
        "go": ["ol", "ol", "ol", "ol", "ol", "ol"],
        "dc": ["cr", "cr"],
        "dm": ["ma", "ma"],
        "dg": ["gu", "gu", "gu"],
        "dh": ["he", "he", "he", "he", "he", "he"],
        "dw": ["wa", "wa"],
        "fl": ["li", "li", "li", "li", "li", "li"],
        "li": ["in", "in", "in", "in", "in", "in"],
        "tb": ["ba", "bo", "bo"],
        "tg": ["gu", "gu"],
        "th": ["he", "he", "he", "he"],
        "tm": ["ma", "ma"],
        "sl": ["la", "la", "la", "la", "la", "la"],
        "la": ["at", "at", "at", "at", "at", "at", "ac", "ac", "ac", "ac", "ac", "ac"],
        "at": ["te", "te", "te", "te", "te", "te"],
        "ni": ["it", "it", "it", "it", "it", "it"],
        "it": ["te", "te", "te", "te", "te", "te"],
        "ha": ["am", "am", "am", "am", "am", "am"],
        "am": ["mm", "mm", "mm", "mm", "mm", "mm"],
        "mm": ["me", "me", "me", "me", "me", "me"],
        "me": ["er", "er", "er", "er", "er", "er"],
        "fa": ["al"],
        "ax": ["xe", "xe", "xe", "xe", "xe", "xe"],
        "xe": ["eg", "eh", "eh", "eb", "eb", "ew"],
        "sh": ["hi", "hi", "hi", "hi", "hi", "hi", "hm", "hg", "hh", "hh", "hb", "hc"],
        "hi": ["ie", "ie", "ie", "ie", "ie", "ie"],
        "ie": ["el", "el", "el", "el", "el", "el"],
        "db": ["ba", "bo", "bo"],
        "mg": ["gu"],
        "mh": ["he"],
        "mb": ["bo"],
        "mw": ["wa"],
        "mc": ["cr"],
        "ms": ["st"],
        "ph": ["ho", "he", "he"],
        "pg": ["gu"],
        "pb": ["bo"],
        "pc": ["cr"],
        "un": ["nd", "nd", "nd", "nd", "nd", "nd"],
        "kh": ["ho", "he", "he", "he", "he"],
        "kg": ["gu", "gu"],
        "kb": ["bo", "bo"],
        "kc": ["cr"],
        "bl": ["la", "la", "la", "la", "la", "la"],
        "km": ["ma"],
        "kw": ["wa"],
        "as": ["sh", "sh", "sh", "sh", "sh", "sh"],
        "hm": ["ma"],
        "hg": ["gu"],
        "hh": ["he", "he"],
        "hb": ["bo"],
        "hc": ["cr"],
        "ru": ["us", "us", "us", "us", "us", "us"],
        "us": ["st", "st", "st", "st", "st", "st"],
        "tw": ["wa"]
      },
      minLen: 6,
      maxLen: 14,
      fallbacks: ["Ironmantle", "Stoneguard", "Greyheart", "Hammerhelm", "Deephold"]
    }
  },
  orc: {
    name: {
      // Bigram table derived from ~200 curated Orc names
      table: {
        "^": ["gr", "ur", "kr", "gr", "du", "th", "mo", "zu", "br", "kr", "gr", "zu", "ur", "gr", "kr", "br", "th", "mo", "du", "zo", "gr", "ur", "kr", "gr", "du", "th", "mo", "zu", "br", "kr", "gr", "zu", "ur", "gr", "kr", "br", "th", "mo", "du", "zu", "gr", "ur", "kr", "gr", "du", "th", "mo", "zu", "br", "kr", "gr", "zu", "ur", "gr", "kr", "br", "th", "mo", "du", "zo", "gr", "ur", "kr", "gr", "du", "th", "mo", "zu", "br", "kr", "gr", "zu", "ur", "gr", "kr", "br", "th", "mo", "du", "zu", "gr", "ur", "kr", "gr", "du", "th", "mo", "zu", "br", "kr", "gr", "zu", "ur", "gr", "kr", "br", "th", "mo", "du", "zo", "gr", "ur", "kr", "gr", "du", "th", "mo", "zu", "br", "kr", "gr", "zu", "ur", "gr", "kr", "br", "th", "mo", "du", "zo", "gr", "ur", "kr", "gr", "du", "th", "mo", "zu", "br", "kr", "gr", "zu", "ur", "gr", "kr", "br", "th", "mo", "du", "zo", "gr", "ur", "kr", "gr", "du", "th", "mo", "zu", "br", "kr", "gr", "zu", "ur", "gr", "kr", "br", "th", "mo", "du", "zo", "gr", "ur", "gr", "du", "th", "mo", "zu", "br", "kr", "go", "go", "go", "zu", "ur", "gr", "kr", "br", "th", "mo", "du", "zo"],
        "gr": ["ra", "ro", "ro", "ro", "ra", "ra", "ri", "ro", "ri", "ro", "ro", "ra", "ra", "ro", "ro", "ro", "ru", "ra", "ro", "ro", "ro", "ru", "ra", "ru", "ro", "ro", "ro", "ra", "ro", "ro", "ro", "ra", "ro", "ro", "ro", "ra", "ro", "ro", "ro", "ra", "ra", "ro", "ro", "ro", "ro", "ro", "ro"],
        "ra": ["ak", "as", "ak", "ak", "ak", "ak", "as", "ak", "ak", "ak", "ak", "ak", "ak", "as", "at"],
        "ak": [".", ".", ".", ".", ".", ".", ".", ".", ".", ".", "ku", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", "kh", ".", ".", ".", ".", ".", "ka", ".", ".", ".", ".", ".", ".", ".", ".", ".", "kn", ".", ".", ".", ".", ".", ".", ".", "kb", ".", ".", ".", ".", ".", ".", ".", "km", "kg", "kr", ".", "."],
        "ur": ["rg", "ra", ".", ".", "rg", "rg", ".", "rg", "rn", ".", "rg", ".", "rg", "rg", ".", "ra", "rg", "rg", "rb", "rg", "rg", "rg", "rn", "rb", "rg", "rg", "rd", "rt", "rg", "rg", "rm", "rl", "rg", "rg", "rg", "rs", "rg", "rg", ".", "ro", "ro", "rg", "ro"],
        "rg": ["go", "ga", "ga", "gr", "gn", "gn", "ga", "gl", "gm", "ga", "gb", "gr", "gb", "gn", "gt", "gm", "gl", "gg", "go", "gs", "gr", "gr"],
        "go": ["ot", "or", "or", "or", "or", "or", "or", "or", "or", "or", "or", "ot", "ot", "ot", "ot", "or", "or", "or", "ot"],
        "ot": ["th", "th", "th", "th", "th", "th", "th", "th", "th", "th", "th", "th", "th", "th", "th", "th", "th", "th", "th", "th", "th", "th"],
        "th": [".", "hr", "hr", "ha", "hr", "hr", "hr", "hr", "hg", "hr", "hr", "hr", "hr", "hb", "hr", "hr", "ht", "hr", "hr", "hl", "hr", "hr", "hs", ".", "hr", ".", ".", ".", ".", ".", "ha", ".", ".", ".", ".", ".", "hr", ".", ".", ".", "hg", "."],
        "kr": ["ru", "ro", "ru", "ru", "ro", "ru", "ru", "ro", "ru", "ru", "ro", "ru", "ru", "ro", "ru", "ru", "ro", "ru", "ru", "ro", "ru", "ru", "ro", "ru", "ru", "ro", "ru"],
        "ru": ["ul", "uk", "ug", "ul", "ub", "ug", "un", "ul", "ul", "uk", "ug", "um", "uk", "ub", "uk", "ug", "um", "ul", "uk", "uk", "ul", "ug", "ub", "ul", "ul", "ug", "ut", "ul", "ul", "ug", "ul", "ul", "ul", "ug", "us", "ul", "uk", "ug", "ug", "ul"],
        "ul": ["la", "la", "la", "la", "ln", "la", "lm", "ln", "lb", "ln", "lt", "lm", "lo", "ll", "lo", "lg", "ls", "lo"],
        "la": ["ar", "ag", "ak", "ak", "as", "as", "ak"],
        "ar": ["."],
        "ro": ["om", "ok", "og", "om", "on", "og", "om", "ok", "og", "om", "on", "og", "om", "og", "ol", "om", "on", "og", "om", "ok", "og", "om", "on", "og", "om", "ok", "og", "om", "on", "og", "om", "ok", "og", "om", "on", "og", "om", "ok", "og", "om", "on", "og", "om", "ok", "og", "om", "on", "og", "om", "ot", "ok", "og", "ot", "ot", "on", "ot", "og", "ot", "ot", "ot"],
        "om": ["mm", "mm", "mn", "mm", "mg", "mn", "mr", "mm", "mn", "mb", "md", "mt", "mm", "ml", "mg", "ms", "mb"],
        "mm": ["ma", ".", "ma", "mu", "mo"],
        "ma": ["as", "ak", "as", "as", "ak", "ak", "ak", "ak", "ak", "ak", "ak", "ak", "ak"],
        "as": ["sh", "sh", "sh", "sh", "sh", "sh", "sh", "sh", "sh", "sh", "sh", "sh", "sh", "sh", "sh", "sh", "sh", "sh", "sh", "sh", "sh", "sh", "sh"],
        "sh": [".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", "."],
        "du": ["ur", "ul", "ur", "un", "ur", "um", "ur", "um", "ur", "ub", "ur", "ut", "ur", "ul", "ur", "us", "ur", "ur"],
        "hr": ["ro", "ro", "ro", "ro", "ro", "ro", "ro", "ro", "ro", "ro", "ro", "ro", "ro", "ro", "ro", "ro", "ro", "ro"],
        "ok": [".", "ku", ".", ".", ".", ".", "ka", ".", ".", "kn", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", "kd", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", "km", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", "kg", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", "ka"],
        "mo": ["og", "og", "og", "og", "og", "og", "og", "og", "og", "og", "og", "og", "ok", "ok", "ok", "ok", "ok", "ok", "og", "ok", "ok", "ok", "ok", "og", "og", "og", "og", "og"],
        "og": ["gu", "gu", "ga", "gr", "gn", "gn", "gn", "gn", "gu", "gg", "gn", "gr", "gb", "gm", "gm", "gm", "gn", "gn", "gb", "gb", "gd", "gd", "gt", "gt", "gm", "gm", "gl", "gl", "gg", "gg", "gs", "gs", "go", "go", "go", "gg"],
        "gu": ["ur", "ur", "ur"],
        "zu": ["ul", "ur", "ug", "ug", "ug", "ug", "ur", "ug", "ur", "ug", "ug", "ur", "ug", "ur", "ug", "ur", "ug", "ur", "ug", "ur"],
        "ag": ["."],
        "br": ["ru", "ru", "ru", "ru", "ru", "ru", "ru", "ru", "ru", "ru", "ru", "ru", "ru", "ru", "ru", "ru", "ru", "ru"],
        "uk": ["kk", "kn", ".", ".", ".", ".", ".", "."],
        "kk": ["."],
        "ga": ["ak", "ak", "ak", "ak", "ak", "ak", "ak", "ak", "ak", "as", "ak", "as", "as"],
        "on": ["na", "nn", "na", "nm", "nb", "nt", "nl", "ns", "no"],
        "na": ["ak", "ak", "ak", "ak", "ak", "ak", "ak", "ak", "ak", "as", "as", "as", "as", "as", "ak", "ak", "ak", "ak", "ak", "ak", "ak"],
        "ug": ["ga", "gr", "ga", "gg", "gr", "gn", "ga", "gm", "ga", "gr", "gn", "gn", "gd", "gd", "gm", "gm", "gg", "gg", "go", "go", "gr"],
        "zo": ["ot", "ot", "ot", "ot", "ot", "ot", "ot"],
        "ha": ["ak", "ak"],
        "ku": ["ur", "ur"],
        "ri": ["im", "im"],
        "im": [".", "."],
        "ub": ["ba", "ba", "bo", "bo"],
        "ba": ["ak", "as", "as", "as", "as", "ak"],
        "mn": ["na", "na", "no"],
        "rn": ["na", "no"],
        "gn": ["na", "na", "na", "no", "no", "na", "na", "na", "na", "na", "na", "na", "no"],
        "gg": ["ga", "ga", "go", "go", "go", "go", "go", "gr"],
        "nn": ["na"],
        "un": ["na", "no"],
        "ln": ["na", "na", "no"],
        "no": ["ok", "ok", "ok", "ok", "ok", "ok", "ok", "ok", "ot"],
        "kh": ["hu"],
        "hu": ["ur"],
        "mg": ["ga", "go"],
        "kn": ["no", "na", "na"],
        "ol": ["la"],
        "gl": ["la", "lo", "lo", "lo"],
        "um": ["ma", "ma", "ma", "ma"],
        "hg": ["ga", "gr"],
        "ka": ["as", "as", "as"],
        "gm": ["ma", "ma", "ma", "ma", "ma", "mo", "mo", "mo", "mo", "mo"],
        "mr": ["ru"],
        "rb": ["ba", "bo", "ba"],
        "gb": ["ba", "ba", "bo", "bo", "bo"],
        "mu": ["uk"],
        "nm": ["ma"],
        "lm": ["ma", "mo"],
        "mb": ["bo", "bu"],
        "bo": ["ok", "ok", "ok", "ok", "ok", "ok", "ok", "ok", "ok", "ok", "ok"],
        "nb": ["bo"],
        "lb": ["bo"],
        "hb": ["bo"],
        "kb": ["bo"],
        "md": ["da"],
        "da": ["ak", "ak", "ak", "ak", "ak", "ak", "ak"],
        "rd": ["da"],
        "kd": ["da"],
        "gd": ["da", "da", "da", "da"],
        "mt": ["to"],
        "to": ["ok", "ok", "ok", "ok", "ok", "ok", "ok", "ok", "ok", "ok"],
        "rt": ["to", "th"],
        "gt": ["to", "to", "to"],
        "nt": ["to"],
        "ut": ["to", "to"],
        "lt": ["to"],
        "ht": ["to"],
        "km": ["mo", "mo"],
        "rm": ["mo"],
        "ml": ["lo"],
        "lo": ["ok", "ok", "ok", "ok", "ok", "ok", "ok", "ok", "ok", "ok", "ot"],
        "rl": ["lo"],
        "nl": ["lo"],
        "ll": ["lo"],
        "hl": ["lo"],
        "kg": ["go", "go"],
        "or": [".", ".", ".", ".", ".", ".", ".", ".", ".", ".", "ra", "rb", "rt"],
        "lg": ["go"],
        "ms": ["so"],
        "so": ["ok", "ok", "ok", "ok", "ok", "ok", "ok", "ok", "ok", "ok"],
        "rs": ["so"],
        "gs": ["so", "so", "so"],
        "ns": ["so"],
        "us": ["so", "so"],
        "ls": ["so"],
        "hs": ["so"],
        "bu": ["ur"],
        "at": ["th"]
      },
      minLen: 3,
      maxLen: 8,
      fallbacks: ["Grak", "Urgoth", "Krular", "Grommash", "Throk"]
    }
  },
  goblin: {
    name: {
      // Bigram table derived from ~200 curated Goblin names
      table: {
        "^": ["ni", "sk", "sn", "gr", "tr", "zi", "pi", "ni", "sn", "gr", "tr", "pi", "sk", "zi", "ni", "sn", "gr", "tr", "pi", "zi", "ni", "sn", "gr", "tr", "pi", "sk", "zi", "ni", "sn", "gr", "tr", "pi", "sk", "zi", "ni", "sn", "gr", "tr", "pi", "sk", "zi", "ni", "sn", "gr", "tr", "pi", "zi", "ni", "sn", "gr", "tr", "pi", "sk", "zi", "ni", "sn", "gr", "tr", "pi", "sk", "zi", "ni", "sn", "gr", "tr", "pi", "sk", "zi", "ni", "sn", "gr", "tr", "pi", "sk", "zi", "ni", "sn", "gr", "tr", "pi", "sk", "zi", "ni", "sn", "gr", "tr", "pi", "sk", "zi", "ni", "sn", "gr", "tr", "pi", "sk", "zi", "ni", "sn", "gr", "tr", "pi", "sk", "zi", "ni", "sn", "gr", "tr", "pi", "sk", "zi", "ni", "sn", "gr", "tr", "pi", "zi", "ni", "sn", "gr", "tr", "pi", "sk", "zi", "ni", "sn", "gr", "tr", "pi", "sk", "zi", "ni", "sn", "gr", "tr", "pi", "sk", "zi", "ni", "sn", "gr", "tr", "pi", "sk", "zi", "ni", "sn", "gr", "tr", "pi", "sk", "zi", "ni", "sn", "gr", "tr", "pi", "sk", "zi", "ni", "sn", "gr", "tr", "pi", "sk", "zi", "ni", "sn", "gr", "tr", "pi", "sk", "zi", "ni", "sn", "gr", "tr", "pi", "sk", "zi", "ni", "sn", "gr", "tr", "pi", "sk", "zi", "ni", "sn", "gr", "tr", "pi"],
        "ni": ["ix", "ik", "ik", "ib", "iz", "it", "ik", "ik", "ik", "ik", "ik", "ik", "it", "ik", "ik", "iz", "ik", "it", "ik", "ik", "ik", "it", "ix", "ix", "ik", "it", "ik", "ik", "ik", "ik", "ik", "it", "ik", "it", "ik", "iz", "ik", "ix", "ix", "ik", "ik", "ik", "ix", "ik", "ik", "ix", "it", "ix", "ik", "ix", "it", "ik", "ik", "ik", "ik", "ik", "it", "ik", "it", "it", "it", "ik", "it", "ix", "it", "ik", "ix", "ik", "ik", "it", "ik", "ix", "ik", "it", "ik", "ik", "ix", "ik", "iz", "ik", "ix", "ix", "ik", "ix", "ik", "ik", "ix", "ik", "ik", "ik", "ix", "ik", "ik", "ik", "ix", "ik", "ik", "ik", "ix", "it", "ik", "it", "it", "it", "it", "it", "it", "ik", "it", "ik", "it", "it", "it", "it"],
        "ix": [".", ".", ".", "xb", ".", "xn", ".", ".", "xk", ".", "xn", ".", "xz", ".", ".", ".", ".", "xs", ".", "xk", "xb", "xr", "xn"],
        "sk": ["kr", "kr", "kr", "kr", "kr", "kr", "kr", "kr", "kr", "kr", "kr", "kr", "kr", "kr", "ki", "ki", "ki", "ki", "kr", "ki", "ki", "ki", "ki", "ki", "kr", "ki", "ki", "ki", "ki", "ki", "ki", "ki", "kr", "ki", "ki", "kr", "kr", "kr", "kr", "kr", "kr", "kr"],
        "kr": ["ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri"],
        "ri": ["it", "ik", "ix", "ik", "iz", "ik", "iz", "ik", "ik", "in", "in", "ik", "iz", "iz", "ik", "iz", "ik", "iz", "ik", "ik", "in", "in", "it", "ik", "iz", "iz", "it", "ik", "ik", "it", "iz", "ik", "it", "iz", "ik", "iz", "ik", "ik", "ik", "iz", "iz", "ik", "ik", "ik", "iz", "iz", "ik", "ix", "ik", "in", "ik", "iz", "ik", "ik", "in", "is", "ik", "iz", "iz", "iz", "ik", "is", "ik", "iz", "ik", "iz", "ik", "iz", "ik", "iz", "ik", "iz", "ik", "iz", "it", "it", "ik", "it", "iz", "it", "it", "ik", "it", "it", "it", "it", "iz", "it", "ik", "it", "it", "iz", "it", "it", "ik", "iz", "ik", "iz", "ik"],
        "it": [".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", "."],
        "sn": ["ni", "ni", "ni", "ni", "ni", "ni", "ni", "ni", "ni", "ni", "ni", "ni", "ni", "ni", "ni", "ni", "ni", "ni", "ni", "ni", "ni", "ni", "ni", "ni", "ni", "ni", "ni", "ni", "ni", "ni", "ni"],
        "ik": ["kb", ".", "kk", "kn", ".", "kk", ".", ".", "kn", ".", "kn", ".", "kk", "kk", "kn", ".", ".", "kk", ".", "ks", ".", "kn", "ks", ".", ".", "kz", ".", ".", "kz", ".", ".", "kn", ".", "kk", "kb", "kn", ".", "kn", "kn", "kn", ".", "kb", "kn", ".", ".", "kk", ".", "kz", ".", "kk", "ks", ".", "kn", "kz", ".", ".", "kz", ".", "kz", ".", ".", "kr", "kb", ".", "kn", "kk", "kr", "kk", "kn", "kk", ".", "kr", ".", "kn", "kr", ".", "kk", "kn", "kb", "kb", "kn", ".", "kb", "kn", ".", "kz", ".", "kn", "kb", "kn", "kn", ".", "kn", "kz", "kk", "kk", "kk", "kn", ".", "kk", "kn", "kz", ".", "ki", "kn", ".", ".", "kr", "kz", ".", ".", "kn", "kb", ".", "kk", "kz", ".", "kk", "ks", "ki", "ks", "kn", ".", "ks", "ks", "ks", "kn", "ks", "ks", "ks", "ks", "ks", "kk", "kk", "kk", "kk", "kk", "kk", "kk", "kk", "kk", "kb", "kb", "kb", "kb", "kb", "kb", "kb", "kb", "kb", "kr", "kr", "kr", "kr", "kr", "kr", "kr", "kr", "kr", "kn", "kn", "kn", "kn", "kn", "kn", "kn", "kn", "kn"],
        "kb": ["bi", "bi", "bi", "bi", "bi", "bi", "bi", "bi", "bi", "bi", "bi", "bi", "bi", "bi", "bi", "bi", "bi", "bi"],
        "bi": ["ik", "ik", "it", "ik", "ik", "it", "it", "it", "it", "ik", "ik", "it", "it", "it", "it", "it", "it", "it", "ik", "it", "it", "it", "it", "it", "it", "it", "it", "it", "it", "it", "it", "it", "it", "it"],
        "gr": ["ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri"],
        "kk": ["ke", "ki", "ki", "ki", "ki", "ki", "ki", "ki", "ki", "ki", "ki", "ki", "ki", "ki", "ki", "ki", "ki", "ki", "ki", "ki", "ki", "ki", "ki", "ki", "ki", "ki", "ki"],
        "ke": ["et"],
        "et": ["."],
        "tr": ["ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri", "ri"],
        "zi": ["ik", "ik", "ik", "ib", "ik", "ik", "ik", "ib", "ik", "ik", "it", "ib", "ik", "ik", "ik", "it", "it", "ib", "it", "ik", "ik", "ib", "ik", "ik", "ik", "ib", "ik", "it", "ib", "it", "ik", "ik", "ik", "ik", "ik", "ib", "ik", "ik", "ik", "ib", "ik", "ib", "ik", "ib", "ik", "ib", "ik", "ib", "ik"],
        "kn": ["ni", "ni", "ni", "ni", "ni", "ni", "ni", "ni", "ni", "ni", "ni", "ni", "ni", "ni", "ni", "ni", "ni", "ni", "ni", "ni", "ni", "ni", "ni", "ni", "ni", "ni", "ni", "ni", "ni", "ni", "ni", "ni", "ni", "ni", "ni", "ni", "ni"],
        "pi": ["ik", "ik", "ik", "ik", "ik", "ik", "ik", "ik", "ik", "ik", "ik", "ik", "ik", "ik", "ik", "ik", "ik", "ik", "ik", "ik", "ik", "ik", "ik", "ik", "ik", "ik", "ik", "ik"],
        "ki": ["it", "it", "it", "ik", "it", "ik", "iz", "it", "it", "ik", "it", "it", "it", "it", "it", "it", "it", "it", "iz", "ix", "it", "it", "it", "it", "it", "it", "it", "it", "it", "it", "it", "it", "it", "it", "it", "it", "it", "it", "it", "it", "it", "it", "it", "it", "it", "it", "it", "it", "it", "it", "it", "it", "it", "it"],
        "ib": ["bb", "bb", "bb", "bn", "bb", "bn", "bb", "bb", "bz", "bn", "bs", "bk", "bb", "br"],
        "bb": ["bi", "bi", "bi", "bi", "bi", "bi", "bi"],
        "iz": ["zi", "zz", "zn", "zb", "zb", "zi", "zz", "zn", ".", "zb", "zn", "zi", "zz", "zz", "zb", "zn", "zn", "zk", "zz", ".", "zn", "zk", "zs", "zs", "zs", "zk", "zk", "zk", "zb", "zb", "zb", "zr", "zr", "zr", "zn", "zn"],
        "zz": ["zi", "zi", "zi", "zi", "zi"],
        "zn": ["ni", "ni", "ni", "ni", "ni", "ni", "ni", "ni"],
        "ks": ["sn", "sn", "sn", "sk", "sk", "sk", "sk", "sk", "sk", "sk", "sk", "sk", "sk"],
        "zb": ["bi", "bi", "bi", "bi", "bi", "bi", "bi"],
        "kz": ["zi", "zi", "zi", "zi", "zi", "zi", "zi", "zi", "zi", "zi", "zi"],
        "in": ["nn", "ni", "nn", "ni", "nz", "ns"],
        "nn": ["ni", "ni"],
        "xb": ["bi", "bi"],
        "bn": ["ni", "ni", "ni"],
        "xn": ["ni", "ni", "ni"],
        "xk": ["ki", "ki"],
        "zk": ["ki", "ki", "ki", "ki", "ki"],
        "xz": ["zi"],
        "nz": ["zi"],
        "bz": ["zi"],
        "ns": ["sk"],
        "is": ["sk", "sk"],
        "xs": ["sk"],
        "zs": ["sk", "sk", "sk"],
        "bs": ["sk"],
        "bk": ["ki"],
        "xr": ["ri"],
        "zr": ["ri", "ri", "ri"],
        "br": ["ri"]
      },
      minLen: 2,
      maxLen: 7,
      fallbacks: ["Nix", "Skrit", "Grikket", "Trix", "Ziknik"]
    }
  },
  beastkin: {
    name: {
      table: {
        "^": ["ss","kh","mr","va","th","pu","sa","fe","ki","ny","ss","kh","mr","va","th","pu","sa","fe","ba","ha","gr","na","ro","wo","ar","ga","ho","ba","ha","ga","ro","wo","ar","gr","na","ho","vi","kr","sa","za","it","va","ne","sk","ra","xe","sa","zi","ve","ne","ra","kr","sa","ze","kr","av","pi","te","ch","fl","sw","kr","ti","pe","av","kr","pi","ti","ch","fl","kr","pe","mu","th","bo","gr","th","bo","ma","to","ga","hu","mu","th","bo","gr","th","bo","ma","tu"],
        "ss": ["si",".","sr","si","se",".","si",".","sa",".","sa","si"],
        "si": ["ir","ik","ik","ik"],
        "ir": ["ra","ra",".",".",".",".","rr","rr","rr"],
        "ra": [".","ak","as",".","at","at","at","ak","as","av","an","ak","ak","au","ak","ax","az","at","az","at",".","aw","aw","au","as","ak","ak","au","ak","ak"],
        "kh": ["he","he"],
        "he": ["et","er"],
        "et": [".",".",".","th",".","th","th","th","th","th"],
        "mr": ["rr","rr"],
        "rr": ["ra","ra","ra","ri","ra","ra","ra","ri","ri",".","ra","ru","ra","ra","ra"],
        "ak": [".",".",".",".",".",".",".",".",".",".",".", "."],
        "va": ["ar","as","ar","as"],
        "ar": ["ri","ri","ra",".","rk","ro","rr","rn","rk","ra","rt",".",".",".",".","rv","rr","rb"],
        "ri": ["is","ix","is","ik","is","iv","ik","ik","ik","iv","im"],
        "is": ["ss","ss",".","ss",".","ss","."],
        "th": ["ha",".",".","ha",".",".",".",".","hi","hi","hk",".","hi","hi","hi",".",".","ha",".",".","ha",".","hu","ha","hu"],
        "ha": ["an","ar","au","ar","ar","ar","au"],
        "an": ["nn","."],
        "nn": ["."],
        "pu": ["ur","ur"],
        "ur": ["rr","rr",".","ra",".","rk","ra","rg","rd","rr","rg","rn","rr"],
        "as": ["sh","sh","sh","sh","ss","sh"],
        "sh": [".","hk",".",".",".","."],
        "sa": ["ah","ah","ar","ar","ar","ar","ar","ar"],
        "ah": ["hk","hr"],
        "hk": ["ke","ke","ke"],
        "ke": ["et","et","es","et"],
        "fe": ["es","es"],
        "es": ["ss","ss",".","ss","ss"],
        "sr": ["ra"],
        "ki": ["ir"],
        "at": ["th",".","th","th","th"],
        "ny": ["ys"],
        "ys": ["ss"],
        "ik": [".",".",".",".",".","kk",".",".",".",".","kr","."],
        "se": ["et"],
        "er": ["rr"],
        "ix": [".",".",".","."],
        "hr": ["ra"],
        "ba": ["ar","au","ar"],
        "au": ["ur","ul","ul","ug","ur","ur","ug","ut","ug","ur","un","ug"],
        "gr": ["ra","ra","ra","ri","ra","ru"],
        "av": ["va","vi","vr"],
        "na": ["au","au","ak"],
        "ul": ["lo","ld"],
        "lo": ["or"],
        "or": [".","rg",".","rr","rr","rr"],
        "ro": ["ow","ou","ow"],
        "ow": ["wa","wr","wg","wb"],
        "wa": ["ar"],
        "rk": [".",".",".","."],
        "wo": ["or","ou"],
        "rg": ["gi",".","."],
        "gi": ["ir","ir","ir"],
        "ou": ["ut","ur"],
        "ut": ["th","th"],
        "ga": ["au","au","ar"],
        "ld": [".","de","."],
        "ho": ["ow","ow"],
        "wr": ["ra","ri"],
        "ug": ["gi","gi","gr","gr"],
        "wg": ["gu"],
        "gu": ["ur"],
        "rn": ["no","no"],
        "no": ["ot","ok"],
        "ot": ["th"],
        "wb": ["ba"],
        "vi": ["iz","ix","it","ik"],
        "iz": ["za"],
        "za": ["as","ar"],
        "kr": ["re","ra","re","ra","re","ra","ri","ri","re","ra","ri"],
        "re": ["et","et","ek","ek","ek"],
        "hi": ["is","ik","ir","is","ix","ir","iv"],
        "ax": ["xe"],
        "xe": ["es","et"],
        "rt": ["th","th"],
        "it": ["th","th","th","th"],
        "ne": ["ex","ex"],
        "ex": ["xi","xs"],
        "xi": ["it"],
        "sk": ["ke"],
        "az": ["zi","zi"],
        "zi": ["is","is","it"],
        "ve": ["ek","ek","ek"],
        "ek": ["kr","kr",".",".","kr",".",".",".",".","kr"],
        "xs": ["sa"],
        "rv": ["vi"],
        "ze": ["ek"],
        "pi": ["ir","ir"],
        "te": ["es"],
        "ch": ["hi","hi"],
        "fl": ["li","li"],
        "li": ["ik","ik"],
        "kk": ["ka"],
        "ka": ["."],
        "sw": ["wi"],
        "wi": ["ip"],
        "ip": ["pp"],
        "pp": ["."],
        "aw": ["wl","wr"],
        "wl": ["."],
        "ti": ["iv","iv"],
        "iv": ["ve","ve","vr","vi","."],
        "pe": ["ek","ek"],
        "vr": ["re","ri"],
        "mu": ["ur","ur"],
        "bo": ["ol","or","ol","ol","or"],
        "ol": ["ld","ld","lr"],
        "de": ["en"],
        "en": ["."],
        "hu": ["un","ur","ur"],
        "un": ["nd","na"],
        "nd": ["do"],
        "do": ["or"],
        "ma": ["au","au"],
        "im": ["."],
        "to": ["or"],
        "ru": ["uk","uk"],
        "uk": [".","."],
        "rb": ["bo"],
        "rd": ["da"],
        "da": ["ak"],
        "lr": ["ra"],
        "ok": ["."],
        "tu": ["ur"]
      },
      minLen: 3,
      maxLen: 10,
      fallbacks: ["Mrrak", "Haur", "Ssira", "Krek", "Tharr"]
    }
  }
};

// --- Word-Combination Data ---

const COMBINE = {
  place: {
    town: {
      prefix: ["Iron", "Stone", "Ash", "Black", "Silver", "Crow", "Elder", "Winter",
        "Thorn", "Oak", "Mist", "Frost", "Bright", "North", "Cross", "Mill",
        "Hollow", "Upper", "Green", "Wood", "Raven", "Storm", "Ember", "Salt", "Grey"],
      suffix: ["haven", "moor", "ford", "bridge", "wick", "stead", "vale", "crossing",
        "hollow", "mill", "gate", "field", "fell", "heath", "water", "wood",
        "croft", "ton", "bury", "ham", "shaw", "den", "holt", "barrow", "mere"]
    },
    building: {
      adjective: ["Broken", "Gilded", "Crooked", "Silent", "Ancient", "Sunken",
        "Burning", "Hollow", "Rusted", "Crumbling", "Amber", "Iron", "Shadow",
        "Ashen", "Pale", "Veiled", "Mossy", "Forgotten", "Twin", "Leaning"],
      type: ["Flagon", "Tower", "Inn", "Hall", "Keep", "Forge", "Mill", "Temple",
        "Vault", "Shrine", "Bridge", "Gate", "Lantern", "Well", "Spire", "Crypt",
        "Cellar", "Archway", "Stockade", "Library"]
    },
    geographic: {
      descriptor: ["Storm", "Iron", "Shadow", "Silver", "Bone", "Ember", "Frost",
        "Ashen", "Crystal", "Dusk", "Grey", "Hollow", "Pale", "Black", "Shattered",
        "Sunken", "Howling", "Verdant", "Salt", "Crimson"],
      feature: ["Ridge", "Fen", "Peaks", "Gorge", "Pass", "Moor", "Vale", "Mere",
        "Wastes", "Forest", "Bay", "Cape", "Reaches", "Narrows", "Cliffs", "Hollow",
        "Expanse", "Marshes", "Strand", "Tor"]
    }
  },
  guild: {
    adjective: ["Silver", "Iron", "Scarlet", "Broken", "Golden", "Black", "Gilded",
      "Hollow", "Crimson", "Pale", "Amber", "Obsidian", "Veiled", "Ashen", "Jade",
      "Azure", "Rusted", "Crowned", "Brazen", "Twinned"],
    symbol: ["Crow", "Hand", "Serpent", "Hammer", "Shield", "Eye", "Coin", "Fang",
      "Lantern", "Brand", "Quill", "Scale", "Blade", "Anchor", "Chain", "Crown",
      "Talon", "Skull", "Compass", "Chalice"]
  },
  item: {
    weapon: {
      material: ["Iron", "Steel", "Ashen", "Bone", "Shadow", "Flame", "Frost", "Silver",
        "Rusted", "Obsidian", "Thornwood", "Blackened", "Gilded", "Hollow", "Cursed",
        "Ancient", "Bloodforged", "Pale", "Venom", "Shattered"],
      type: ["Blade", "Sword", "Axe", "Spear", "Dagger", "Bow", "Hammer", "Maul",
        "Cleaver", "Halberd", "Mace", "Flail", "Glaive", "Shortblade", "Waraxe",
        "Crossbow", "Pike", "Saber", "Falchion", "Dirk"],
      epithet: ["Fallen", "Sorrow", "Undying", "Hollow", "Pale", "Wretched", "Broken",
        "Damned", "Forsaken", "Lost", "Last", "Bitter", "Silent", "Blind", "Endless"]
    },
    armour: {
      material: ["Iron", "Hardened", "Gilded", "Bone", "Shadow", "Blessed", "Ruined",
        "Ancient", "Tarnished", "Blackened", "Scaled", "Woven", "Reinforced", "Pale",
        "Ashen", "Silvered", "Cracked", "Burnished", "Hollowed", "Cursed"],
      type: ["Plate", "Mail", "Hauberk", "Breastplate", "Shield", "Helm", "Pauldron",
        "Cuirass", "Greaves", "Coif", "Vambrace", "Gorget", "Gauntlets", "Tasset",
        "Mantle", "Surcoat", "Brigandine", "Lamellar", "Byrnie", "Aventail"],
      epithet: ["Vanguard", "Fallen King", "Last Stand", "Pale Court", "Iron Throne",
        "Shattered Wall", "Hollow Crown", "Forsaken", "Warden", "Bloodied Dawn",
        "Broken Siege", "Sunken Keep", "Lost Order", "Enduring", "Condemned"]
    },
    potion: {
      form: ["Tincture", "Draught", "Elixir", "Brew", "Distillation", "Essence",
        "Phial", "Vial", "Infusion", "Decoction"],
      ingredient: ["Brackwater", "Ember Root", "Shadow Moss", "Moonpetal",
        "Ironbark", "Foxglove", "Pale Ash", "Thornblood", "Cinder", "Goldleaf",
        "Stillwater", "Nightshade Resin", "Briarwood", "Salted Dusk", "Hollow Fern",
        "Ashbone", "Mistwood", "Bloodpetal", "Frostvein", "Greywort", "Sunstone",
        "Blackdew", "Emberthorn", "Pale Glass", "Copperleaf"]
    }
  }
};

// --- Generators ---

function generatePersonName(culture, variant) {
  const data = CULTURES[culture];
  if (!data) {
    setStatus("Unknown culture: " + culture);
    return null;
  }

  if (culture === "human") {
    const variantData = data[variant];
    if (!variantData) {
      setStatus("Unknown variant: " + variant);
      return null;
    }
    if (variant === "surname") {
      return "> 👤 Human Surname: " + markovName(variantData);
    }
    const first = markovName(variantData);
    const surname = markovName(data.surname);
    const label = variant === "male" ? "Human Male" : "Human Female";
    return "> 👤 " + label + ": " + first + " " + surname;
  }

  if (culture === "dwarf") {
    const personal = markovName(data.name);
    const clan = markovName(data.clan);
    return "> 👤 Dwarf: " + personal + " " + clan;
  }

  // All other cultures: single name pool
  const label = culture.charAt(0).toUpperCase() + culture.slice(1);
  return "> 👤 " + label + ": " + markovName(data.name);
}

function generatePlaceName(subtype) {
  switch (subtype) {
    case "town":
      return "> 🏰 Place (Town): " + combine([COMBINE.place.town.prefix, COMBINE.place.town.suffix]);
    case "building":
      return "> 🏰 Place (Building): The " + combine([COMBINE.place.building.adjective, [" "], COMBINE.place.building.type]);
    case "geographic":
      return "> 🏰 Place (Geographic): " + combine([COMBINE.place.geographic.descriptor, [" "], COMBINE.place.geographic.feature]);
    default:
      return null;
  }
}

function generateGuildName() {
  return "> 📜 Guild: The " + combine([COMBINE.guild.adjective, [" "], COMBINE.guild.symbol]);
}

function generateItemName(subtype) {
  if (subtype === "weapon" || subtype === "armour") {
    var data = COMBINE.item[subtype];
    var base = combine([data.material, [" "], data.type]);
    if (Math.random() < 0.3) {
      return "> ⚔️ Item (" + cap(subtype) + "): " + base + " of the " + pick(data.epithet);
    }
    return "> ⚔️ Item (" + cap(subtype) + "): " + base;
  }
  if (subtype === "potion") {
    return "> ⚔️ Item (Potion): " + combine([COMBINE.item.potion.form, [" of "], COMBINE.item.potion.ingredient]);
  }
  return null;
}

// --- UI Wiring ---

document.getElementById("btn-namegen-person").addEventListener("click", () => {
  const culture = document.getElementById("namegen-culture").value;
  const variant = document.getElementById("namegen-variant").value;
  const result = generatePersonName(culture, variant);
  if (result) {
    insertAtCursor(result);
  }
});

document.getElementById("namegen-culture").addEventListener("change", function () {
  const variantEl = document.getElementById("namegen-variant");
  variantEl.hidden = this.value !== "human";
});

document.getElementById("btn-namegen-place").addEventListener("click", () => {
  const subtype = document.getElementById("namegen-place-type").value;
  const result = generatePlaceName(subtype);
  if (result) {
    insertAtCursor(result);
  }
});
