import { insertAtCursor, setStatus } from "./app.js";

// --- Utilities ---

function pick(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

// --- Markov Engine ---

function markovName(cfg) {
  const { table, minLen, maxLen, fallbacks } = cfg;
  let attempts = 0;
  while (attempts < 100) {
    let state = pick(table["^"]);
    let name = state;
    let steps = 0;
    while (steps < 20) {
      const successors = table[state];
      if (!successors) break;
      const token = pick(successors);
      if (token === ".") break;
      name += token[1];
      state = token;
      steps++;
    }
    const capitalised = name[0].toUpperCase() + name.slice(1).toLowerCase();
    if (capitalised.length >= minLen && capitalised.length <= maxLen) {
      return capitalised;
    }
    attempts++;
  }
  const fallback = pick(fallbacks);
  return fallback[0].toUpperCase() + fallback.slice(1).toLowerCase();
}

// --- Culture Data ---

const CULTURES = {
  human: {
    male: {
      table: {
        "^": ["al", "ed", "ro", "wu", "go", "ha", "le", "br", "th", "ed", "ro", "al", "ga", "ce", "os", "wi", "be", "co", "si", "ra", "er", "ba", "gu", "he", "in", "lo", "ma", "no", "os", "re", "st", "to", "ul", "va", "we", "al", "bj", "cl", "di", "el", "ea", "go", "ha", "le", "ro", "si", "wa", "al", "be", "ea", "fa", "ge", "ha", "iv", "jo", "ke", "la", "me", "ni", "od", "pe", "ra", "so", "th", "ul", "vi", "wu", "al", "co", "dr", "er", "fe", "gi", "ha", "ir", "jo", "ke", "lo", "ma", "ni", "os", "pe", "qu", "ra", "si", "to", "ut", "va", "we", "al", "br", "ca", "de", "ed", "fo", "ga", "ha", "in", "ja", "ka", "le", "mo", "ni", "or", "ph", "ro", "st", "tr", "ut", "va", "wa", "ad", "bo", "co", "da", "el", "fe", "go", "ha", "is", "ja", "ke", "li", "ma", "no", "os", "pa", "re", "sv", "th", "ul", "vi", "wo", "ar", "br", "co", "di", "eg", "fl", "gr", "ha", "iv", "jo", "kn", "lu", "me", "nj", "or", "pr", "ru", "se", "th", "ul", "vi", "wy", "al", "be", "co", "dr", "ed", "fa", "gr", "ha", "is", "ja", "ke", "lo", "mi", "ne", "oe", "pr", "ra", "sk", "th", "ul", "va", "wi", "an", "bo", "ce", "da", "ed", "fe", "gu", "ha", "is", "jo", "ke", "lo", "ma", "no", "os", "pe"],
        "al": ["ld", "ld", "la", "ld", "ld", "ld", "ld", "ld", "ld", "lk", "ld", "ld", "ld", "ls", "ld", "ll", "ld", "ld", "ld", "lr", "ld", "lv", ".", "ld", "lv", "ld", "ld", "lr", "ld", "lo", "lv", "lr"],
        "ld": ["dr", ".", "dr", ".", "de", "dw", "da", "de", "do", ".", "dr", "dr", "dr", "dh", "de", "de", "dr", ".", ".", ".", ".", "dr", "."],
        "dr": ["ri", "ri", "ri", "ri", "ri", "ri", "re", "ru", "ri", "ri", "ri", "ri", "ri", "re", "ri", "ri", "ri", "ra", "ri", "ri", "ri"],
        "ri": ["ic", "ic", "ic", "in", "ic", "ic", "ic", "ic", "ic", "ik", "ic", "ic", "ic", "ic", "ik", "ic", "ic", "ic", "ic", "ic", "in", "ic", "ic", "ic", "ic", "ic", "ic", "ic", "is", "ic", "ic", "ic", "ic", "ig", "ic", "ia", "if", "ic", "ik", "ic", "im", "ic", "ic", "ic", "is", "ic", "ic", "ic", "ic", "in"],
        "ic": [".", ".", ".", ".", ".", ".", ".", ".", ".", "ch", ".", ".", ".", ".", ".", ".", ".", ".", ".", "ck", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", "ce", ".", ".", ".", ".", "."],
        "ed": ["dm", "dr", "dr", ".", "de", ".", "dr", "dw", ".", "dr", ".", "dg", "dw", "dm"],
        "dm": ["mu", "mu", "mo"],
        "mu": ["un", "un", "un", "un", "un", "un", "un", "un", "un"],
        "un": ["nd", "nd", "nt", "nd", "nd", "nd", "nd", "nd", "nd", "nd", "nd", "nd"],
        "nd": [".", ".", ".", ".", "de", "dr", ".", ".", "do", "de", ".", "dr", ".", ".", ".", ".", ".", ".", ".", "dr", "."],
        "ro": ["ol", "ow", "od", "on", "or", "on", "os", "os"],
        "ol": ["la", "lm", "lf", "lf", "lb", "ld"],
        "la": ["an", "ar", "ar", "an", "an", "an", "as", "an", "an"],
        "an": ["nd", ".", ".", ".", "nd", ".", ".", "nd", ".", ".", ".", "nd", "nt", ".", ".", ".", "ne", ".", "nd", ".", "ns", "."],
        "wu": ["ul", "ul"],
        "ul": ["lf", "lr", "lf", "lf", "lf", "la", "lb", "."],
        "lf": ["fr", "fr", ".", "fs", ".", "fr", "fr"],
        "fr": ["ri", "ri", "re", "re", "ra"],
        "go": ["od", "od", ".", "od", "oo"],
        "od": ["dw", "dr", "de", "di", "de", "dm", "."],
        "dw": ["wi", "wi", "wi", "wy", "wi"],
        "wi": ["in", "il", "in", "in", "in", "in", "il", "in"],
        "in": [".", ".", ".", "ng", "nh", ".", ".", ".", ".", "ng", ".", ".", ".", "nn", "."],
        "ha": ["ar", "ar", "ar", "al", "ar", "al", "al", "al", "al", "an", "ag", "am", "al"],
        "ar": ["ra", "ri", "re", ".", ".", ".", "rd", ".", "rd", "rd", ".", "rs", "rr", "re", "re", "ro", "rd", "rl", ".", "ru", ".", ".", "rd", "ra"],
        "ra": ["al", "ad", "ag", "am", "ag", "an", "an", "am", "am", "al", "av", "al", "ag"],
        "le": ["eo", "ea", "eo"],
        "eo": ["of", "or", "on", "or"],
        "of": ["fr"],
        "br": ["re", "ra", "ry", "re"],
        "re": ["en", "et", "ed", "ei", "en", "ed", "ed", "en", "es", "et", "ed", "ek", "el", "ei", "ed", "en", "en", "ec", "eg"],
        "en": ["nn", "nr", ".", ".", ".", ".", "nd", ".", ".", "nr", ".", ".", "nd", ".", ".", ".", "nd", ".", ".", ".", ".", "nz", "nt"],
        "nn": ["na", "."],
        "na": ["an", "ar"],
        "th": ["ho", ".", "he", "ha", "he", "he", ".", "hr", "ha", "ho", "ho", "ho"],
        "ho": ["or", "or", "ol", "or"],
        "or": ["ri", "rn", "rb", "rs", "rn", ".", "ri", "re", "rm", "rc", "rn", "re", "rr", "ri", "rt", "ri", "ri", "rw", "rc", ".", "ri", "rg", "rm", "ra", "rm", "re", ".", "rv", ".", "ri", "rd"],
        "ow": ["wa"],
        "wa": ["an", "al", "ar", "al", "al"],
        "ga": ["ar", "ar", "ar"],
        "et": ["th", "tr", "th", "ti"],
        "ce": ["ed", ".", ".", "ed"],
        "os": ["sr", "sw", "sb", "ss", "sg", "sp", "sm"],
        "sr": ["ri", "ri"],
        "il": ["lf", "ls", "ll", "lh", "."],
        "be": ["eo", "er", "er", "er", "er"],
        "rn": [".", "ne", ".", "."],
        "co": ["on", "ol", "or", "ol", "or"],
        "on": ["nr", ".", ".", ".", "nd", ".", "nd"],
        "nr": ["ra", "ri", "ri"],
        "ad": [".", "dw", "dr", "do", "dr"],
        "si": ["ig", "ig", "ig"],
        "ig": ["gm", "gu", "gg", "gr", ".", "gm"],
        "gm": ["mu", "mu"],
        "ag": ["gn", "gn", "gn", "ge", "gn", "gf"],
        "gn": ["na", "nu", "nv", "no"],
        "er": ["rw", ".", "rt", "rn", ".", ".", "ri", "rt", "rh", "rr", ".", "ro", "rl", "rr", ".", ".", "rt", "rr", ".", "rt", ".", "ri", "rg", "re"],
        "rw": ["wi", "wi"],
        "ba": ["al"],
        "gu": ["un", "ur", "us", "un"],
        "nt": ["th", ".", "ti"],
        "he": ["er", "en", "er", "er", "el", "el", "el"],
        "ik": [".", ".", "kl", "kt", ".", "ka"],
        "ng": ["gv", "gr"],
        "gv": ["va"],
        "va": ["ar", "al", "ar", "al", "al", "ar", "ar", "ar", "ar", "al", "al"],
        "lo": ["ot", "ov", "or", "or", "or", "or", "ot"],
        "ot": ["th", "tr"],
        "ma": ["ag", "ar", "al", "ad", "ac", "al"],
        "nu": ["us", "ut"],
        "us": [".", "st", ".", "."],
        "no": ["or", "or", "or", "or"],
        "rb": ["be"],
        "rt": [".", "tr", "te", ".", "th"],
        "sw": ["wa"],
        "ei": ["in", "id"],
        "nh": ["ha"],
        "rd": [".", ".", "de", ".", ".", ".", "dr"],
        "st": ["te", "te", "ta", "ta", "te", ".", "te", "ta", "ta"],
        "te": ["ef", "en", "en", "en", "ef"],
        "ef": ["ff", "fa", ".", "."],
        "ff": ["fe", "fi"],
        "fe": ["en", "en", "en", "er"],
        "to": ["or", "or", "or"],
        "rs": ["st", "se"],
        "lr": ["ri", "ri", "ri", "ri", "ri"],
        "de": ["em", "er", "er", "en", "en", "er", "eo", "el", "er", "es", "en", "en"],
        "em": ["ma"],
        "we": ["er", "en"],
        "ne": ["er", ".", "el"],
        "bj": ["jo"],
        "jo": ["or", "or", "or", "or", "ok"],
        "cl": ["lo"],
        "ov": ["vi"],
        "vi": ["is", "ig", "ik", "ig"],
        "is": [".", "st", "sr", "sm", ".", "sl"],
        "di": ["ie", "in", "ir"],
        "ie": ["et", "ef", "ef"],
        "tr": ["ri", "ra", "ri", "ri"],
        "ch": [".", "ht"],
        "el": ["lm", "ll", ".", "lm", ".", "la", "ld", ".", "lr", "ld", ".", "ls", "lm", "lm"],
        "lm": ["mu", ".", ".", ".", "."],
        "ea": ["ad", "an", "am"],
        "da": ["an", "ar", "ar", "ag", "an"],
        "ur": ["rd"],
        "am": [".", "mo", ".", ".", "mu"],
        "mo": ["on", "on", "or", "on"],
        "fa": ["al", "an", "ar"],
        "lk": ["."],
        "ge": ["er", "en", "en"],
        "rh": ["ha"],
        "do": ["or", "ol", "oc"],
        "iv": ["va", "va"],
        "ke": ["en", "el", "ed", "el", "et"],
        "se": ["en", "el", "el"],
        "me": ["er", "er"],
        "rr": ["ri", "ri", "re", "ri", "ri"],
        "ni": ["il", "ia", "ik"],
        "ls": [".", "st", "."],
        "pe": ["ed", "er", "er", "er", "er"],
        "nv": ["va"],
        "so": ["or"],
        "gg": ["go"],
        "fs": ["st"],
        "ta": ["an", "an", "an", "an"],
        "ru": ["us", "un", "uf"],
        "rl": ["la", "."],
        "gi": ["id"],
        "id": ["de", "da"],
        "ir": ["re", "rk"],
        "rm": ["mu", ".", "ma"],
        "ll": ["la", ".", "la"],
        "rc": ["ca", "cr"],
        "ca": ["an", "al"],
        "ia": ["al", "an"],
        "sb": ["bo"],
        "bo": ["or", "od", "or"],
        "qu": ["ui"],
        "ui": ["il"],
        "gr": ["ri", "ra", "ri", "ri", "ri", "ri"],
        "ut": ["th", "th", "."],
        "dh": ["he"],
        "es": ["sm", "st"],
        "sm": ["mo", "mu", "mu"],
        "wy": ["yn", "ys"],
        "yn": ["."],
        "fo": ["or"],
        "ck": ["."],
        "ja": ["ar", "ar", "al", "as"],
        "ka": ["ae", "ae", "al"],
        "ae": ["el", "el"],
        "kl": ["la"],
        "as": [".", "sp"],
        "ph": ["he"],
        "hr": ["re"],
        "ek": ["."],
        "lv": ["va", "va", "vd"],
        "li": ["ie", "ie"],
        "oc": ["."],
        "cr": ["ro"],
        "ss": ["."],
        "sg": ["go"],
        "oo": ["od"],
        "pa": ["ad"],
        "sv": ["ve"],
        "ve": ["en", "en"],
        "kt": ["to"],
        "wo": ["ol"],
        "ry": ["yc"],
        "yc": ["ce"],
        "lb": ["be", "br"],
        "rk": ["."],
        "eg": ["gr", "gr"],
        "fl": ["lo"],
        "if": ["ff"],
        "fi": ["in", "in"],
        "rg": ["ge", "gu"],
        "kn": ["nu"],
        "lu": ["ud"],
        "ud": ["dr"],
        "nj": ["ja"],
        "pr": ["ro", "re"],
        "sp": ["pe", "pe"],
        "uf": ["fu"],
        "fu": ["us"],
        "ys": ["st"],
        "ac": ["."],
        "av": ["ve"],
        "dg": ["ga"],
        "im": ["mw"],
        "mw": ["wa"],
        "nz": ["."],
        "mi": ["ik"],
        "oe": ["er"],
        "ti": ["ic", "il"],
        "sk": ["ka"],
        "rv": ["va"],
        "ec": ["ch"],
        "ht": ["."],
        "lh": ["he"],
        "ns": ["se"],
        "gf": ["fi"],
        "vd": ["da"],
        "sl": ["li"],
        "ok": ["ku"],
        "ku": ["ul"]
      },
      minLen: 4,
      maxLen: 10,
      fallbacks: ["Aldric", "Edmund", "Gareth"]
    },
    female: {
      table: {
        "^": ["mi", "ed", "ro", "wi", "gw", "al", "su", "br", "el", "fr", "hi", "in", "ka", "li", "as", "si", "th", "yr", "da", "ei", "gu", "he", "is", "ra", "sv", "th", "ul", "va", "ae", "be", "el", "ge", "li", "ma", "ne", "pe", "so", "to", "wy", "al", "br", "ed", "fe", "gi", "hr", "id", "jo", "ke", "la", "ma", "no", "ol", "re", "si", "to", "un", "vi", "wr", "as", "da", "ey", "fr", "gu", "he", "in", "ju", "ka", "li", "ma", "nj", "od", "ra", "si", "th", "ul", "vi", "yl", "al", "bo", "ce", "di", "el", "fr", "gr", "he", "il", "jo", "kj", "lo", "ma", "no", "ol", "ra", "si", "tu", "ur", "va", "ae", "be", "da", "em", "fj", "gu", "ha", "in", "ja", "ko", "lj", "my", "ne", "oy", "ra", "sk", "to", "un", "vi", "we", "as", "br", "ce", "do", "es", "fo", "gr", "hj", "id", "jo", "ka", "lo", "ma", "na", "od", "ru", "sa", "ti", "un", "va", "al", "bi", "cl", "da", "ei", "fr", "ge", "he", "il", "ja", "ko", "li", "mo", "ne", "ot", "re", "sv", "th", "ul", "ve", "ar", "bo", "do", "ey", "fa", "gr", "ha", "in", "jo", "kr", "lj", "mo", "ni", "ol", "ra", "si", "th", "ul", "va"],
        "mi": ["ir"],
        "ir": ["ra", "ra", "rn", ".", "ra"],
        "ra": [".", ".", ".", ".", "ag", ".", ".", ".", "an", "an", "ag", ".", ".", ".", ".", ".", "ak", "ag"],
        "ed": ["di", "dl", "dd", "di"],
        "di": ["it", "it", "is", "is", "is", "il", "il", "is", ".", "is", "is", "is", "is", "is"],
        "it": ["th", "th", "th", "tt"],
        "th": [".", ".", "ho", "hy", ".", "ha", "ha", ".", "ho", "hi", "he", "hi", "hu", "hr", "ho"],
        "ro": ["ow", "oa"],
        "ow": ["we"],
        "we": ["en", "en", "en", "en"],
        "en": ["na", ".", ".", "nn", ".", ".", "nd", "nd"],
        "na": [".", ".", ".", ".", ".", ".", ".", "au", ".", ".", "."],
        "wi": ["il"],
        "il": ["ll", "ld", "ld", "ld", "ld", ".", "ld", "la", "ld", ".", "ls", "ld", "lj", "lb", "ly", "ld", "ld", "ld", "ld", "ld", "ld", "ld", "ld"],
        "ll": ["la", "la", "lf", "la", "lv", "la", "lb"],
        "la": [".", "ar", ".", ".", ".", "ag", ".", ".", "au", ".", ".", ".", ".", "au", ".", "."],
        "gw": ["we"],
        "al": ["ld", "ld", "ld", "lv", "ll", "ll", "lf", "ll", "lg"],
        "ld": ["di", ".", "da", "de", "di", ".", "da", "da", ".", ".", ".", "de", ".", ".", "de", ".", ".", "dr", ".", ".", "."],
        "su": ["un"],
        "un": ["nn", ".", "nn", "nn", "nn", ".", "nv", ".", "nn", "nn", "na", "nn", "nn", "nn", "nn", "."],
        "nn": ["ni", "ne", "ne", "na", ".", "na", "nh", "ne", ".", ".", "nr", ".", ".", "."],
        "ni": ["iv", "il", "id"],
        "iv": ["va", "vi", "ve"],
        "va": [".", "al", ".", ".", ".", ".", "an", "ar", "an", "al"],
        "br": ["ry", "ri", "ru", "re"],
        "ry": ["yn"],
        "yn": ["nh", "nn", "."],
        "nh": ["hi", "hi", "hi", "hi", "he"],
        "hi": ["il", "il", "il", "il", "il", "il", "il", "il", "il", "il", "il", "il"],
        "el": ["la", "lg", "li", "lf", "la", "ld", "li", "lk", "ll"],
        "ar": ["ra", "re", "ra", ".", "ri", "rn", "ra", "rn", "rn"],
        "fr": ["re", "ri", "re", "ri", "ri", "ri", "ri", "ru"],
        "re": ["ey", "en", "ef", "ev", "en", "ej", "et", "en", "eg"],
        "ey": ["ya", "yd", "yf"],
        "ya": ["."],
        "da": [".", "ag", ".", "ar", ".", "ag", ".", ".", "al", ".", ".", "ag", "."],
        "in": ["ng", "nn", ".", "ng", ".", "ng", "ne", "nd", "nl", "ng"],
        "ng": ["gr", "ga", "ge", "ge", "gu"],
        "gr": ["ri", "ri", "ru", "re", "ro", "ri"],
        "ri": ["id", "id", "id", "it", "is", "in", "il", "id", "in", "ik", "id", "id", "id", "id", "id", "id", "in", "ig", ".", "im"],
        "id": [".", ".", ".", "dr", "da", ".", ".", "da", ".", ".", "du", ".", "db", "."],
        "ka": ["at", "ar", ".", ".", "at", "at", "."],
        "at": ["tl", "th", "tr", "tl"],
        "tl": ["la", "le", "la"],
        "li": ["in", "it", "iv", "is", "ia", "in"],
        "ne": ["ea", "es", ".", ".", ".", "er", ".", "er"],
        "ea": [".", "."],
        "as": ["st", "st", "sl", "st"],
        "st": ["tr", "ta", "tr", "tv"],
        "tr": ["ri", "ra", "ri", "ri"],
        "si": ["ig", "ig", "ig", "il", "ig"],
        "ig": ["gr", ".", "gn", "gd", ".", "gr", ".", "gg", "gv"],
        "ho": ["or", "or", "or"],
        "or": ["ra", "ru", "ri", "ri", "rh", "rn", ".", "rg", "rd", "rg", "rt", "rd", ".", "rg", "rg", "ra", "rg", "rg", ".", "rd"],
        "yr": ["rs", "ra", "rt"],
        "rs": ["sa", "sa"],
        "sa": [".", ".", ".", ".", ".", ".", "ax", "ag"],
        "ag": ["gn", "gn", "ge", "gn", "gm", "gn", "gn", "ga", "gn", "gn"],
        "gn": ["ny", "na", "nh", "ne", "nf", "ni", "na", "ny", "nh"],
        "ny": [".", ".", "."],
        "ei": ["ir", "ig", "ig", "ig", "ir", "ir", "if", "id"],
        "gu": ["ud", "un", "un", "un", "un", "un"],
        "ud": ["dr", "."],
        "dr": ["ru", "ri", "ri", "."],
        "ru": ["un", "un", "un", "un", "un", "ud", "un"],
        "he": ["el", "er", "ed", ".", "er", "ei"],
        "lg": ["ga", "ge"],
        "ga": [".", ".", "."],
        "is": ["so", ".", "se", ".", ".", ".", "sb", "sa", "sa", ".", ".", ".", ".", "."],
        "so": ["ol", "ol"],
        "ol": ["ld", "lv", "lw", "la", "la", "la", "lb", "lk", "ll", "lo"],
        "de": [".", ".", "."],
        "sv": ["ve", "va"],
        "ve": ["ea", "ei", "ei", "ek", "ei", "ed"],
        "hy": ["yr"],
        "ul": ["ll", "lr", "ld", "lf", "lf"],
        "ae": ["el", "ev", "es"],
        "be": ["er", "et", "er", "er"],
        "er": ["rt", "rd", "rt", "rt", "rg", "ri", "rv", "rd", "rt", "ra", "rd"],
        "rt": ["ta", "th", "th", "tl", "th", "th"],
        "ta": [".", ".", ".", ".", ".", "."],
        "lf": ["fh", "fr", "fh", "fh", "fr"],
        "fh": ["hi", "hi", "hi"],
        "ge": ["er", "er", "eb", "ei", "er", "er"],
        "rd": ["da", "di", "di", "dr", "di", "da"],
        "vi": ["ia", "ig", "iv", "is", "il", ".", "."],
        "ia": [".", "."],
        "ma": ["ar", "ag", "ar", "ae", "at", "ag", "."],
        "es": ["ss", "sa", "st"],
        "ss": ["sa"],
        "pe": ["et"],
        "et": ["tr", "th", "ta"],
        "lv": ["ve", "va", "va", "ve"],
        "to": ["ov", "or", "or"],
        "ov": ["va", "vi"],
        "wy": ["yn"],
        "tt": ["ta", "ta", "ta"],
        "dl": ["ly", "la"],
        "ly": ["yn", "."],
        "fe": ["en"],
        "gi": ["is", "in"],
        "se": ["el", "."],
        "hr": ["re", "ru"],
        "ef": ["fn"],
        "fn": ["na", "."],
        "jo": ["or", "ol", "oh", "ot", "ol", "or", "or", "of", "or", "or", "ot", "or"],
        "ke": ["el", "."],
        "ha": [".", ".", "an", "al", "al"],
        "no": ["or", "or"],
        "lw": ["we"],
        "ev": ["vn", "va"],
        "vn": ["na"],
        "gd": ["di"],
        "wr": ["re"],
        "gm": ["ma"],
        "yd": ["di", "di"],
        "ju": ["ut", "uf"],
        "ut": ["tt"],
        "sb": ["be"],
        "nj": ["jo", "ja"],
        "od": ["di", "di", "dd", "dg"],
        "an": ["nv", "nn", "nd", "nj", "nh"],
        "nv": ["ve", "vo"],
        "rh": ["hi"],
        "lr": ["ri"],
        "ik": ["ka"],
        "ek": ["ka"],
        "yl": ["lv"],
        "bo": ["od", "or", "or"],
        "ce": ["el", "ec"],
        "lk": ["ke", "kv"],
        "ej": ["ja"],
        "ja": [".", ".", "ar", "ar"],
        "dd": ["da", "dn"],
        "ls": ["se"],
        "oh": ["ha"],
        "kj": ["je"],
        "je": ["el", "."],
        "lo": ["ov", "of", "ot", "of"],
        "rn": ["na", "ns", "na", "ng", "nb"],
        "au": ["ug", "ug", "um"],
        "ug": [".", "."],
        "nd": ["di", "dl", "da", "."],
        "lj": ["je", "jo", "ju", "jo"],
        "tu": ["ur"],
        "ur": ["ri", "rs", "ra"],
        "rg": ["gl", ".", ".", ".", "gn", "gu", "."],
        "gl": ["lj"],
        "ot": [".", "th", "tk", "tt", "."],
        "em": ["mb"],
        "mb": ["bl"],
        "bl": ["la"],
        "fj": ["jo"],
        "vo": ["or", "or", "or"],
        "eb": ["bj"],
        "bj": ["jo", "jo", "jo"],
        "ns": ["sa"],
        "ax": ["xa"],
        "xa": ["."],
        "ko": ["ol", "ol"],
        "lb": ["br", "bo", "be"],
        "uf": ["fa"],
        "fa": [".", "as"],
        "my": ["yr"],
        "le": [".", "ei"],
        "oy": ["yd"],
        "nf": ["fr"],
        "sk": ["ku"],
        "ku": ["ul"],
        "sl": ["la"],
        "ec": ["ci"],
        "ci": ["il"],
        "do": ["or", "ot"],
        "fo": ["ol"],
        "kv": ["vi"],
        "oa": ["."],
        "hj": ["jo"],
        "du": ["un"],
        "of": ["fr", "fn", "."],
        "um": ["ma"],
        "dn": ["ny"],
        "ti": ["il"],
        "nr": ["."],
        "bi": ["ir"],
        "cl": ["lo"],
        "gg": ["."],
        "rv": ["vo"],
        "mo": ["od", "or"],
        "dg": ["gu"],
        "hu": ["us"],
        "us": ["."],
        "tk": ["ka"],
        "eg": ["gi"],
        "nl": ["le"],
        "if": ["."],
        "nb": ["bj"],
        "yf": ["fu"],
        "fu": ["ur"],
        "tv": ["vi"],
        "im": ["mh"],
        "mh": ["hi"],
        "kr": ["ra"],
        "ak": ["ka"],
        "db": ["bj"],
        "gv": ["vo"]
      },
      minLen: 3,
      maxLen: 10,
      fallbacks: ["Mira", "Freya", "Astrid"]
    },
    surname: {
      table: {
        "^": ["th", "co", "bl", "as", "wr", "du", "ir", "st", "oa", "ra", "wi", "gr", "ha", "br", "mo", "co", "de", "fa", "go", "he", "ki", "lo", "ni", "ol", "pi", "qu", "re", "si", "ta", "un", "wo", "as", "br", "du", "el", "fo", "gr", "ho", "iv", "ke", "ma", "no", "oa", "pe", "ro", "st", "th", "wh", "ya", "bl", "co", "du", "ea", "fe", "gr", "ha", "ir", "la", "mo", "ni", "ov", "pi", "ra", "sh", "th", "un", "va", "we", "as", "br", "cr", "da", "el", "fr", "gl", "ha", "ir", "je", "ke", "li", "mo", "ne", "oa", "py", "ri", "st", "th", "ul", "va", "wi", "al", "bi", "cl", "de", "ed", "fi", "gl", "hi", "ir", "ju", "kn", "le", "ma", "no", "oa", "ra", "sh", "ta", "up", "va", "wy", "as", "br", "cr", "da", "em", "fe", "gr", "hi", "ir", "ja", "ki", "la", "mi", "no", "oa", "pi", "ro", "st", "tu", "un", "va", "wi", "al", "br", "co", "de", "ev", "fo", "go", "he", "iv", "je", "ke", "lo", "mi", "ne", "ov", "pi", "ro", "si", "th", "um", "va", "wi", "as", "ba", "cl", "da", "ea", "fe", "gi", "he", "in", "ja", "ke", "la", "me", "no", "oa", "pe", "ro", "st", "ta", "ul", "va", "wi"],
        "th": ["ho", ".", "hs", "ho", ".", "hg", "ho", "ho", "ho", "hi", ".", "he", "ho", ".", ".", "hm", "ha", ".", "hw", ".", ".", "ho", "hf", "ho"],
        "ho": ["or", "ol", "or", "ol", "or", "ol", "ol", "or", "ol", "ol", "or", "ol", "ol", "or", "ol", "or"],
        "or": ["rn", ".", "rd", "re", "rt", "rf", "rn", "rt", "rt", "rn", "rn", "re", ".", "rt", ".", "rg", "rm", "rn", "rt", ".", "rn", "rt", "rt", ".", "rt", "rt", ".", "rt", "rt", "re", "rn", ".", "rw", "rn", "."],
        "rn": ["nw", "ne", ".", "nb", ".", "nd", ".", "nf", "ne", "ns", "nw", "nw", "."],
        "nw": ["wo", "wo", "wa", "wi"],
        "wo": ["oo", "or", "ol", "oo", "or", "oo", "oo", "oo", "oo", "or", "oo", "oo", "oo", "or", "oo", "oo", "or", "oo", "oo", "or", "or", "oo", "oo"],
        "oo": ["od", "or", "or", "ok", "od", "ok", "od", "od", "od", "ok", "od", "or", "or", "od", "or", "or", "od", "od", "od", "or", "od", "od", "or", "od", "od", "ok", "or", "od", "or"],
        "od": [".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", "."],
        "co": ["ol", "op", "oa", "oa"],
        "ol": ["ld", "ll", "ld", "ld", "lf", "ll", "ll", "lm", "ll", "lm", "lm", "ll", "ld", "lm"],
        "ld": ["dw", ".", "dl", "dc", "de", ".", ".", ".", "dm", ".", "de", ".", ".", "dg", "dc", ".", ".", "dh", ".", ".", "."],
        "dw": ["we"],
        "we": ["el", "es", "el", "el"],
        "el": ["ll", "lm", "ld", "ld", "ld", "ld", "lm", "ld", "ll", "ld", "ld", "ll", "ld", "ll", "ld", "ll", "lm", "ll", "ld", "ld", "ld", "ld", "ld"],
        "ll": [".", "lo", ".", "lo", ".", "lo", "lo", "lo", ".", ".", ".", ".", ".", "lf", "lo", "lw", "lc", "lh", ".", "ls", "lc", ".", "lo", "lm"],
        "bl": ["la", "la", "le"],
        "la": ["ac", "ac", "ak", "ay", "ar", "ar"],
        "ac": ["ck", "ck", "ck"],
        "ck": ["km", "ks", ".", "kw", "ke", ".", "."],
        "km": ["mo", "me", "mo"],
        "mo": ["oo", "or", "oo", "os", "or", "oo", "oo", "on", "oo", "oo", "oo", "oo", "or", "oo", "oo"],
        "as": ["sh", "st", "sh", "st", "sh", "sh", "st", "sh"],
        "sh": ["hf", "ha", "hw", "ha", "he", "hi", "ha", "hm", "ha", "hd", "hc"],
        "hf": ["fo", "fi"],
        "fo": ["or", "ox", "ox"],
        "rd": [".", "da", "da", ".", "da"],
        "wr": ["re"],
        "re": ["en", ".", "ey", ".", "ed", ".", ".", ".", "ee", ".", ".", ".", "eh", "es", ".", ".", ".", "es", ".", "ey", "es", ".", ".", ".", ".", "es", ".", "es", ".", ".", ".", "es", ".", ".", "es"],
        "en": ["ns", "nc", "nd", "nm", ".", "nh", "ns", "nm", "nd", "nd", "nh", "nm", ".", ".", "nm", ".", "."],
        "ns": ["sh", "sc", "si", "st"],
        "ha": ["aw", "aw", "aw", "av", "aw", "ad", "ar", "ad", "av", "av", "av", "av"],
        "aw": [".", "wk", ".", "wt", "wn"],
        "du": ["un", "us", "un"],
        "un": ["nm", "nd", "nh", "nd", "ni", "nd"],
        "nm": ["mo", "ma", "mo", "mo", "me", "me", "me"],
        "ir": ["ro", "rw", "ro", "ro", "rc", "rs", "ro", "ro"],
        "ro": ["on", "of", "oo", "ov", "oo", "os", "ow", "on", "oo", "os", "on", "of", "on", "on", "os", "of", "of", "oo", "of", "ow", "ow", "of", "os"],
        "on": ["nv", "ne", "ne", "ng", "ne", "nb", "ns", "nd", ".", "ne", "nh", "ne", ".", "ne", "nm", "ne", "ng", "ne"],
        "nv": ["va"],
        "va": ["al", "al", "al", "al", "al", "as", "al", "al", "al"],
        "al": ["le", "ll", "ll", "lb", "le", "le", "le", "ln", "ld", "le", "ll", "le", "ll", "le", "le", "ld", "lh", "le", "le", "le", "lm", "le", "ll", "le"],
        "le": [".", "ea", ".", "ew", ".", ".", "ed", "eb", "ew", "en", "en", ".", "ed", ".", "ew", ".", "ew", ".", ".", "ew", ".", ".", "ec", "em", "em"],
        "st": ["to", "to", "tl", ".", "to", "tm", "tl", "tm", "tf", "to", ".", "to", "to", "to", "th", "to", ".", "te", "ta", "to", "tm", ".", "tm", ".", ".", "to", "."],
        "to": ["on", "on", "on", "or", "on", "on", "on", "on", "on", "on", "on"],
        "ne": ["eh", ".", ".", ".", "eh", ".", "ec", "ew", "et", ".", ".", ".", ".", "ew", ".", "et", "ec", "eb"],
        "eh": ["he", "hu", "hi"],
        "he": ["el", "ea", "en", "er", "ea", "el", "ea"],
        "lm": [".", "me", "me", "ms", ".", "ms", "me", "me", "me"],
        "oa": ["ak", "ak", "al", "ak", "ak", "ak", "al", "ak"],
        "ak": ["kr", "ks", "ke", "kh", "kv", "ke", "kh"],
        "kr": ["ri"],
        "ri": ["id", "ig", "ia", "im", "id", "in", "iv", "id"],
        "id": ["dg", "dg", "de", "ds", "dg"],
        "dg": ["ge", "ge", "ge", "ge", "ga", "ge"],
        "ge": [".", ".", "ew", "ew", "."],
        "ra": ["av", "av", "ag", "av", "ac", "am", "av"],
        "av": ["ve", "ve", "ve", "ve", "ve", "ve", "ve", "ve", "ve"],
        "ve": ["en", "er", "er", ".", ".", "en", "er", "en", "er", "er", "en", "en", "en", "en", "er", "er", "er", "er", "en", "."],
        "nc": ["cr"],
        "cr": ["ro", "ro", "ra", "ro", "re", "re", "re", "ro", "re", "ro", "re", "ro", "re", "ro", "re"],
        "of": ["ft", "ft", "ft", "ft", "ft", "ft"],
        "ft": [".", ".", ".", ".", ".", "."],
        "wi": ["in", "in", "ic", "in", "in", "in", "ic", "il", "ic", "in"],
        "in": ["nt", "nd", "ng", "ne", "ne", "nd", "nw", "nd", "ng", "nd", "ne", "nt", "ne", "nk", "nd"],
        "nt": ["te", "te"],
        "te": ["er", "er", ".", ".", "ec", "er", ".", "ea", "er", ".", "er"],
        "er": ["rb", ".", "rg", "re", ".", "rb", "re", "rh", "rg", "re", ".", "re", "rn", "rd", "re", "rw", "re", "rc", "rb", "rs", "re", "rm", "re", ".", "re", "rt", "re", "rg", "re", "re", "re", "rc", "rf", "re", "rd", "rh", "rv", "rf", "re", "re", "re", "rd", "rn", ".", "re", "re"],
        "rb": ["bo", "br", "be"],
        "bo": ["ou", "or"],
        "ou": ["ur"],
        "ur": ["rn", "rs", "ry", "rn", "rn"],
        "gr": ["re", "ro", "ri", "re", "re", "ra"],
        "ey": ["ym", "ys"],
        "ym": ["ma", "me"],
        "ma": ["an", "ar", "ar", "ar", "ar", "ai"],
        "an": ["ne", "ne"],
        "wk": ["ks"],
        "ks": ["sw", "si", "sh"],
        "sw": ["wo", "wo", "wo", "wo", "wa"],
        "rt": ["th", "th", "th", "th", "th", "tw", ".", "th", "th", "th", "to", "th", "th", "th", "th"],
        "br": ["ri", "ro", "ri", "ro", "ri", "ra", "ra", "ri"],
        "ig": ["gh", "gh", "gh", "gh", "gh"],
        "gh": ["ht", "ht", "ht", "hc", "ht"],
        "ht": ["tw", "tf", "th", "tf"],
        "tw": ["wa", "we"],
        "wa": ["at", "at", "at", "ar", "at", "at"],
        "at": ["te", "te", "te", "te", "te", "tc", "te", "tc", "th", "te"],
        "rf": ["fi", "fe", "fi"],
        "fi": ["ie", "ie", "ie", "ie", "ir", "ie", "ie", "ie", "ie", "ie", "ie", "ie"],
        "ie": ["el", "el", "el", "el", "el", "el", "el", "el", "el", "el", "el", "el"],
        "op": ["pp"],
        "pp": ["pe", "pe"],
        "pe": ["er", "en", "er", "er", "ew"],
        "rg": ["ga", "gr", "ga", "gl"],
        "ga": ["at", "at", "at", "at"],
        "de": ["ee", "er", "er", "er", ".", "er", "ee", "ew", "er", "ew"],
        "ee": ["ep", "en", "ep"],
        "ep": ["ph", "pm"],
        "ph": ["ho"],
        "lo": ["ow", "on", "ow", "ov", "ow", "ow", "ow", "ow", "ow", "on", "ow", "ov"],
        "ow": [".", "wm", "wf", ".", ".", ".", "wm", "wn", ".", ".", "wm", "wm", ".", "wc"],
        "fa": ["ai", "al", "al"],
        "ai": ["ir", "id"],
        "rw": ["wi", "wo", "wo"],
        "nd": [".", "de", ".", "da", "de", "dl", ".", ".", "dm", "da", "dh", ".", "de", "dc"],
        "go": ["ol", "ol"],
        "dl": ["le", "le"],
        "ea": ["af", "ar", "as", "ar", "ad", "ag", "at", "ad"],
        "af": ["."],
        "ar": ["rt", "rk", "rc", "rs", "rk", "rr", "rk", ".", "rc", "rk", "rt", "rt", "rl", "rk", "rk", "rd", "rr", "rk", "rr", "rk"],
        "hs": ["st"],
        "ki": ["in", "in"],
        "ng": ["gs", "gm", "gs", "gd"],
        "gs": ["sm", "sw"],
        "sm": ["ma", "mo"],
        "rk": [".", ".", ".", "kh", "km", "kf", "km", "kf"],
        "gm": ["me", "mo"],
        "me": ["er", "er", "er", "er", ".", "er", ".", "er", "er", "er", "er", "er", "er", "er", "er", "er", "er", "er", "er", ".", "er", "ea", "er"],
        "ni": ["ig", "ig", "ip", "ig"],
        "tf": ["fa", "fi", "fa"],
        "dc": ["ca", "cr", "cr"],
        "ca": ["as", "ar"],
        "tl": ["le", "le", "le", "le", "le"],
        "pi": ["in", "in", "in", "in"],
        "hu": ["ur"],
        "rs": ["st", "sh", "st", "st"],
        "qu": ["ui"],
        "ui": ["ic"],
        "ic": ["ck", "ck", "ck", "ck"],
        "si": ["il", "il", "id", "il"],
        "il": ["lv", "lv", "ll", "ll", "ll", "ll", "ll", "ll", "ll", "lv", "ll", "ld"],
        "lv": ["ve", "ve", "ve", "ve"],
        "ed": ["dt", "do", "dg", "dg"],
        "dt": ["th"],
        "ok": [".", "kh", ".", "kf"],
        "ta": ["al", "al", "ar", "al"],
        "wm": ["me", "me", "me", "me", "me"],
        "rh": ["hi", "hi"],
        "hi": ["il", "ie", "it", "is", "il", "ig", "il", "il", "il"],
        "lf": ["fs", "fi"],
        "fs": ["sb"],
        "sb": ["ba"],
        "ba": ["an", "ar", "ar"],
        "hw": ["wi", "wo", "wi"],
        "ia": ["ar"],
        "rc": ["cl", "ch", "cr", "ch", "cr"],
        "cl": ["li", "li", "la", "li", "lo"],
        "li": ["if", "if", "in", "if"],
        "if": ["ff", "ff", "ff"],
        "ff": [".", ".", "."],
        "us": ["sk"],
        "sk": ["kw"],
        "kw": ["wo", "wa", "wa"],
        "ov": ["ve", "ve", "ve", "ve", "ve"],
        "ox": ["xg", "xw"],
        "xg": ["gl"],
        "gl": ["lo", "le", "le", "lo", "le"],
        "im": ["ms"],
        "ms": ["sh", "sw", "sw"],
        "wf": ["fi", "fi"],
        "iv": ["vy", "ve", "vy"],
        "vy": ["ym", "yw"],
        "ke": ["et", "ew", "el", "en", "en", "el", "et"],
        "et": ["tt", "th", "tt", "tt", "th"],
        "tt": ["tl", "tl", "tl"],
        "ew": ["wo", "wo", "wo", "wo", "wo", "wo", "we", "wo", "wa", "wo", "wo", "wm", "wi", "wf"],
        "no": ["or", "or", "or", "or", "or"],
        "hg": ["ga"],
        "kh": ["ha", "ho", "he", "ha"],
        "ec": ["cr", "cl", "cr", "cr"],
        "os": ["ss", "ss", "st", "se", "se"],
        "ss": [".", "sr"],
        "nb": ["bu", "ba"],
        "bu": ["ur", "ur"],
        "ry": ["."],
        "wh": ["hi"],
        "it": ["te"],
        "ya": ["ar"],
        "rr": ["ro", "ro", "ro"],
        "lb": ["bu"],
        "nh": ["ho", "ho", "ho", "hi"],
        "tm": ["me", "ma", "mo", "mo"],
        "fe": ["er", "el", "el", "er"],
        "da": ["al", "al", "ar", "al", "al", "aw", "al", "al", "al", "ar"],
        "wt": ["th"],
        "sr": ["ri"],
        "sc": ["ca"],
        "ad": ["do", "de", ".", "do"],
        "do": ["ow", "ow", "ow"],
        "is": ["st"],
        "wn": [".", "nm"],
        "eb": ["br", "br"],
        "es": ["st", "sm", "st", "st", "st", "st", "st", "st", "st", "st"],
        "ch": [".", "hw", ".", "."],
        "hm": ["mo", "me"],
        "ag": ["gm", "gl"],
        "fr": ["ro"],
        "je": ["es", "es"],
        "dm": ["me", "me"],
        "py": ["yr"],
        "yr": ["re"],
        "be": ["en", "er", "er"],
        "rm": ["mc", "mo"],
        "mc": ["cr"],
        "nf": ["fi"],
        "ul": ["lv", "lg"],
        "ln": ["no"],
        "bi": ["ir"],
        "ay": ["yb"],
        "yb": ["bo"],
        "pm": ["me"],
        "hc": ["cl", "cr"],
        "ju": ["un"],
        "ip": ["pe"],
        "kn": ["ni"],
        "ds": ["st"],
        "kv": ["va"],
        "up": ["pp"],
        "wy": ["yn"],
        "yn": ["nd"],
        "dh": ["ho", "ho"],
        "hd": ["da"],
        "em": ["mb", "me", "mo"],
        "mb": ["be", "bl", "be"],
        "lw": ["wo"],
        "ys": ["st"],
        "lc": ["cr", "cr"],
        "ja": ["ar", "ar"],
        "rl": ["ls"],
        "ls": ["st", "sw"],
        "mi": ["il", "il"],
        "lh": ["ha", "ha"],
        "tc": ["ch", "ch"],
        "se": ["ew", "et"],
        "kf": ["fi", "fi", "fi"],
        "tu": ["ur"],
        "am": ["mb"],
        "ev": ["ve"],
        "xw": ["wo"],
        "yw": ["wo"],
        "gd": ["da"],
        "rv": ["va"],
        "um": ["mb"],
        "gi": ["il"],
        "nk": ["kw"],
        "wc": ["cr"],
        "lg": ["gr"]
      },
      minLen: 5,
      maxLen: 14,
      fallbacks: ["Thornwood", "Ashford", "Ironvale"]
    }
  }
};

// --- Generators ---

function generatePersonName(culture, variant) {
  const data = CULTURES[culture];
  if (!data) {
    setStatus("Unknown culture: " + culture);
    return null;
  }
  const variantData = data[variant];
  if (!variantData) {
    setStatus("Unknown variant: " + variant);
    return null;
  }
  if (variant === "surname") {
    const surname = markovName(variantData);
    return "> 👤 Human Surname: " + surname;
  }
  const first = markovName(variantData);
  const surname = markovName(data.surname);
  const label = variant === "male" ? "Human Male" : "Human Female";
  return "> 👤 " + label + ": " + first + " " + surname;
}

// --- UI Wiring ---

document.getElementById("btn-namegen-person").addEventListener("click", () => {
  const culture = document.getElementById("namegen-culture").value;
  const variant = document.getElementById("namegen-variant").value;
  const result = generatePersonName(culture, variant);
  if (result) {
    insertAtCursor(result);
  }
});
